gympass/yoga

packages/yoga/src/Checkbox/web/Switch.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Switch.test.jsx.snap
=> [Switch] Add thumb shadow on hover

.github/workflows/npmpublish.yml, package.json, packages/doc/package.json, packages/yoga/package.json, packages/yoga/scripts/notify.js
At every new **@gympass/yoga** release, our Slack will receive this notification with the release URL (_version_) and the Yoga documentation URL (_Check it out!_):
=> [DS-94] Slack integration

packages/doc/content/getting-started/index.mdx, packages/doc/package.json, packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/ComponentTitle/ComponentTitle.jsx, packages/doc/src/components/Documentation/Documentation.jsx, packages/doc/src/components/Dropdown/Dropdown.jsx, packages/doc/src/components/Header/Header.jsx, packages/doc/src/components/InlineCode/InlineCode.jsx, packages/doc/src/components/Layout/Footer.jsx, packages/doc/src/components/Layout/Layout.jsx, packages/doc/src/components/Navigation/Navigation.jsx, packages/doc/src/components/PropsTable/PropsTable.jsx, yarn.lock
=> [DS-102] Responsive design

packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/InlineCode/InlineCode.jsx, packages/doc/src/components/Navigation/Navigation.jsx
=> [DS-102] Responsive doc

.github/workflows/npmpublish.yml, packages/doc/content/components/components/button/link-native.mdx, packages/doc/content/components/components/button/link-web.mdx, packages/doc/content/components/components/button/link.mdx, packages/labnative/pages/Button.jsx, packages/yoga/src/Button/index.js, packages/yoga/src/Button/index.native.js, packages/yoga/src/Button/native/Button.test.jsx, packages/yoga/src/Button/native/Link.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/Button.test.jsx, packages/yoga/src/Button/web/Link.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Slider/native/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Slider/web/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Theme/themes/BaseTheme.js, packages/yoga/src/Theme/themes/EndUser.js
=> [DS-131] Link button

packages/yoga/src/Button/web/Button.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Card/web/Card.jsx, packages/yoga/src/Card/web/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Checkbox/web/CheckMark.jsx, packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Checkbox/web/Switch.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap, packages/yoga/src/Checkbox/web/__snapshots__/Switch.test.jsx.snap, packages/yoga/src/List/web/List.jsx, packages/yoga/src/List/web/ListItem.jsx, packages/yoga/src/List/web/__snapshots__/List.test.jsx.snap, packages/yoga/src/RadioGroup/web/RadioButton.jsx, packages/yoga/src/RadioGroup/web/RadioGroup.jsx, packages/yoga/src/RadioGroup/web/__snapshots__/RadioButton.test.jsx.snap, packages/yoga/src/RadioGroup/web/__snapshots__/RadioGroup.test.jsx.snap, packages/yoga/src/Slider/native/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Slider/web/Marker.jsx, packages/yoga/src/Slider/web/Slider.jsx, packages/yoga/src/Slider/web/Tooltip.jsx, packages/yoga/src/Slider/web/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Stepper/web/Dots.jsx, packages/yoga/src/Stepper/web/Line.jsx, packages/yoga/src/Stepper/web/Stepper.jsx, packages/yoga/src/Stepper/web/__snapshots__/Stepper.test.jsx.snap, packages/yoga/src/Theme/themes/BaseTheme.js
This PR changes:
- Props destructuring from styled-components;
- Add `box-sizing` to some components that need it;
- Add `css` function;
=> [DS-128] Refactor components

packages/doc/content/components/components/slider/slider-web.mdx, packages/doc/content/guidelines/tokens/borders.mdx, packages/doc/content/guidelines/tokens/colors.mdx, packages/doc/content/guidelines/tokens/elevations.mdx, packages/doc/content/guidelines/tokens/font-sizes.mdx, packages/doc/content/guidelines/tokens/font-weights.mdx, packages/doc/content/guidelines/tokens/fonts.mdx, packages/doc/content/guidelines/tokens/index.mdx, packages/doc/content/guidelines/tokens/line-heights.mdx, packages/doc/content/guidelines/tokens/radii.mdx, packages/doc/content/guidelines/tokens/spacing.mdx, packages/doc/src/components/Documentation/Documentation.jsx, packages/doc/src/components/Tokens/Cards.jsx, packages/doc/src/components/Tokens/Colors.jsx, packages/doc/src/components/Tokens/Tag.jsx, packages/doc/src/components/Tokens/Tokens.jsx, packages/doc/src/components/Tokens/Wrapper.jsx, packages/doc/src/components/Tokens/index.js, packages/doc/src/components/Tokens/withToken.jsx, packages/doc/src/components/index.js, packages/tokens/src/global/colors.js
In this PR I'm adding the design tokens documentation:
=> [DS-76] Design Tokens Documentation

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/native/PlanCard/Content.jsx, packages/yoga/src/Card/native/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
=> [DS-64] Better Plan Card documentation

packages/doc/content/components/components/card/plancard-web.mdx, packages/doc/content/guidelines/product-content/grammar-and-mechanics/index.mdx, packages/doc/content/guidelines/product-content/index.mdx, packages/doc/content/guidelines/product-content/key-points/index.mdx, packages/doc/content/guidelines/product-content/voice-and-tone/index.mdx, packages/doc/content/guidelines/product-content/web-elements/index.mdx, packages/doc/content/guidelines/product-content/word-list/index.mdx, packages/doc/content/guidelines/product-content/writing-about-people/index.mdx, packages/doc/content/guidelines/product-content/writing-for-accessibility/index.mdx, packages/doc/content/guidelines/product-content/writing-for-translation/index.mdx, packages/doc/content/guidelines/tokens/index.mdx, packages/doc/gatsby-node.js, packages/doc/src/components/Documentation/Documentation.jsx, packages/doc/src/components/Img/Img.jsx, packages/doc/src/components/Img/index.js, packages/doc/src/components/Navigation/Navigation.jsx, packages/doc/src/components/Navigation/tree.js, packages/doc/src/components/index.js, packages/doc/src/templates/docs.jsx, packages/doc/src/templates/nav.js
This PR adds a way to order the content written in the packages/doc. You just need to add an `order` property inside the `frontmatter` section, in your `mdx` file, and the package will do the magic for you. 
```
---
title: 'A beautifull text'
metaTitle: 'A beautifull metaTitle text'
metaDescription: 'A beautifull metaDescription'
order: 0
---
```
=> [DS-129] Sort documentation

packages/yoga/src/Card/native/PlanCard/PlanCard.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
=> fix(plancard): remove default props from ribbon in PlanCard

packages/labnative/ios/Podfile.lock, packages/labnative/pages/Button.jsx, packages/yoga/src/Button/native/Button.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/native/withTouchable.jsx, packages/yoga/src/Card/native/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap
This PR adjusts the alignment on Button component.
=> [DS-143] Button alignment fix

packages/doc/content/components/components/card/default-web.mdx, packages/yoga/src/Card/native/Card/Card.jsx, packages/yoga/src/Card/native/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/PlanCard.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/Card/Card.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Theme/themes/BaseTheme.js
In this PR I'm adding a feature to set a variant color and intensity in the `Card` component.
**This feature fixes the bug in the Issue #73**
=> [DS-144] Card Variant Intensity

packages/doc/content/components/components/grid/index.mdx, packages/labnative/ios/Podfile.lock, packages/yoga/src/Button/native/Button.jsx, packages/yoga/src/Button/native/Link.jsx, packages/yoga/src/Button/native/Outline.jsx, packages/yoga/src/Button/native/Text.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/Link.jsx, packages/yoga/src/Button/web/Outline.jsx, packages/yoga/src/Button/web/StyledButton.jsx, packages/yoga/src/Button/web/Text.jsx, packages/yoga/src/Card/native/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Theme/themes/BaseTheme.js
This:
isn't happening anymore
😂
=> Fix Android Button borders

packages/doc/content/components/components/themeprovider/index.mdx, packages/doc/content/components/getting-started/index.mdx
Getting Started was updated, the installation mode was missing the styled-component installation.
ThemeProvider has been adjusted from every word in the prop to PascalCase.
=> docs((docs)): updating documentation, Getting Started and ThemeProvider

packages/doc/content/guidelines/tokens/fonts.mdx, packages/doc/gatsby-browser.js, packages/doc/gatsby-config.js, packages/doc/src/components/Tokens/Tokens.jsx, packages/doc/static/fonts.css, packages/tokens/src/global/fonts.js, packages/yoga/package.json, packages/yoga/src/Button/web/StyledButton.jsx, packages/yoga/src/Text/textStyle.jsx, packages/yoga/src/Theme/Provider/web/GlobalStyle.jsx, packages/yoga/src/Theme/Provider/web/GlobalStyle.test.jsx, packages/yoga/src/Theme/Provider/web/expectCssMatches.js, packages/yoga/src/Theme/themes/BaseTheme.js, scripts/prepublish.js, yarn.lock
In this PR I'm removing the font import with `@import` and using a third party library `react-google-font-loader` to solve the problem to import google fonts.
=> [DS-161] Fixing font import in web GlobalStyle

.github/workflows/npmpublish.yml, packages/doc/content/components/components/text/default-web.mdx, packages/yoga/src/Theme/Provider/index.js, packages/yoga/src/Theme/Provider/web/FontLoader.jsx, packages/yoga/src/Theme/Provider/web/FontLoader.test.jsx, packages/yoga/src/Theme/Provider/web/GlobalStyle.jsx, packages/yoga/src/Theme/Provider/web/index.js, packages/yoga/src/Theme/index.js, packages/yoga/src/Theme/index.native.js, packages/yoga/src/index.js, yarn.lock
All Yoga components uses its own font family based on font design token provided by the `<ThemeProvider />`, if you are using Server Side Rendening (SSR) you need to import the `<FontLoader />` in your `<Head>`.
```
import { ThemeProvider, FontLoader } from '@gympass/yoga';
import Head from 'next/head';
<ThemeProvider>
<Head>
<title>My page title</title>
<FontLoader />
</Head>
<h1>Hey Gympass</h1>
</ThemeProvider>
```
=> fix(theme): fixing font import on SSR

packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/native/__snapshots__/TextArea.test.jsx.snap
=> fix(input): fix field height on native

packages/doc/content/components/components/input/default-native.mdx, packages/doc/content/components/components/input/email-native.mdx, packages/doc/content/components/components/input/number-native.mdx, packages/doc/content/components/components/input/password-native.mdx, packages/doc/content/components/components/input/tel-native.mdx, packages/doc/content/components/components/textarea/textarea-native.mdx, packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/Password.jsx, packages/yoga/src/Input/native/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Wrapper.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/TextArea.jsx, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
Fix the disabled state and the full width in the `Field` component that is used in both components, `TextArea` and `Input`.
Also, fix some paddings
=> Fix TextArea

packages/doc/content/components/components/progress/progress-native.mdx, packages/doc/content/components/components/progress/progress-web.mdx, packages/labnative/pages/Progress.jsx, packages/yoga/src/Progress/native/Progress.jsx, packages/yoga/src/Progress/native/Progress.test.jsx, packages/yoga/src/Progress/native/__snapshots__/Progress.test.jsx.snap, packages/yoga/src/Progress/web/Progress.jsx, packages/yoga/src/Progress/web/Progress.test.jsx, packages/yoga/src/Progress/web/__snapshots__/Progress.test.jsx.snap, packages/yoga/src/Theme/themes/components/progress.js
Add variant prop.
Ex:
`<Progress variant="secondary" />`
=> [DS-173] Progress variant

packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/native/TextArea.jsx, packages/yoga/src/TextArea/web/TextArea.jsx, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
When updating the value prop the UI is updated as well.
Closes #111
=> [DS 178] Input/TextArea fix

packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
=> [DS-163] PlanCard behavior inside Grid/Col component

packages/doc/content/components/components/button/index.mdx, packages/doc/content/components/components/card/gym/index.mdx, packages/doc/content/components/components/card/index.mdx, packages/doc/content/components/components/checkbox/index.mdx, packages/doc/content/components/components/dropdown/dropdown-native.mdx, packages/doc/content/components/components/dropdown/dropdown-web.mdx, packages/doc/content/components/components/input/index.mdx, packages/doc/content/components/components/radiogroup/index.mdx, packages/doc/content/components/components/radiogroup/radio-native.mdx, packages/doc/content/components/components/rating/rating-native.mdx, packages/doc/gatsby-node.js, packages/doc/src/components/Navigation/Navigation.jsx, packages/doc/src/components/Navigation/tree.js, packages/doc/src/templates/docs.jsx, packages/doc/src/templates/nav.js, packages/icons/package.json, packages/yoga/src/Dropdown/native/Dropdown.jsx, packages/yoga/src/Dropdown/web/Dropdown.jsx
In this PR I'm adjusting the Dropdown documentation to show examples about `selected` option, as a **plus** I'm adjusting the Navigation to open just the first level of menu.
=> Adjusting Dropdown documentation

packages/doc/content/components/components/list/list-web.mdx, packages/yoga/src/List/index.js, packages/yoga/src/List/web/LinkItem.jsx, packages/yoga/src/List/web/List.test.jsx, packages/yoga/src/List/web/ListLinkItem.jsx, packages/yoga/src/List/web/__snapshots__/List.test.jsx.snap, packages/yoga/src/List/web/index.js
We want to be able to click on the full area of the item. To do that, we need to apply the styles directly to the anchor tag.
Since we need this, we should create a new compound.
=> Create <List.LinkItem />

.github/labeler.yml, .github/workflows/labeler.yml, CONTRIBUTING.md, packages/common/README.md, packages/tokens/README.md
=> Update contribute guidelines

package.json, packages/labnative/babel.config.js, packages/labnative/customTransformer.js, packages/labnative/ios/Podfile.lock, packages/labnative/metro.config.js, packages/labnative/pages/Card.jsx, packages/yoga/src/Card/native/Card/Card.jsx, packages/yoga/src/Card/native/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/native/EventCard/EventCard.jsx, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/native/GymCard/CheckIn/__snapshots__/CheckIn.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/EventCard/EventCard.jsx, packages/yoga/src/Card/web/EventCard/__snapshots__/EventCard.test.jsx.snap, yarn.lock
In this PR I'm adjusting the Card component with `overflow:hidden`
=> fix(card): adjusting card shadow and event-card style

packages/tokens/src/global/colors.js, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Checkbox/native/__snapshots__/Checkbox.test.jsx.snap, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap, packages/yoga/src/Progress/native/__snapshots__/Progress.test.jsx.snap, packages/yoga/src/Progress/web/__snapshots__/Progress.test.jsx.snap, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/web/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Theme/themes/Corporate.js
We have a color pallete in Clients/Corp that doesn't match the one provided. So we need to change it.
* Add color `buenosAires`;
* Change primary color from Corporate theme to `buenosAires`;
* Change secondary color from Corporate theme to `newYork`;
=> Change Corporate theme colors

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap
- New property box-sizing for field input
=> New property box-sizing in component input

packages/yoga/src/Theme/themes/Kids.js, packages/yoga/src/Theme/themes/index.js
- Added `Kids` as a theme into Yoga
=> feat(theme): added kids theme into yoga

packages/tokens/src/global/spacing.js, packages/yoga/src/AutoComplete/AutoComplete.theme.js, packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Card/Card.theme.js, packages/yoga/src/Card/native/Card/Card.jsx, packages/yoga/src/Card/native/PlanCard/Actions.jsx, packages/yoga/src/Card/web/Card/Card.jsx, packages/yoga/src/Card/web/PlanCard/Actions.jsx, packages/yoga/src/Checkbox/Checkbox.theme.js, packages/yoga/src/Checkbox/CheckboxSwitch.theme.js, packages/yoga/src/Checkbox/web/Switch.jsx, packages/yoga/src/Dropdown/Dropdown.theme.js, packages/yoga/src/Input/Input.theme.js, packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/Password.jsx, packages/yoga/src/Input/web/Password.jsx, packages/yoga/src/Input/web/Wrapper.jsx, packages/yoga/src/List/List.theme.js, packages/yoga/src/Progress/Progress.theme.js, packages/yoga/src/Progress/native/Progress.jsx, packages/yoga/src/Progress/web/Progress.jsx, packages/yoga/src/RadioGroup/RadioGroup.theme.js, packages/yoga/src/Rating/Rating.theme.js, packages/yoga/src/Slider/Slider.theme.js, packages/yoga/src/Tag/Tag.theme.js
`spacings` tokens changes:
|Token|Old value|New Value|
|------|---------|-----------|
|zero|0|0|
|xxxsmall|-|4|
|xxsmall|4|8|
|xsmall|8|12|
|small|12|16|
|medium|16|20|
|large|20|24|
|xlarge|24|32|
|xxlarge|40|40|
|xxxlarge|56|56|
|huge|72|72|
|xhuge|-|80|
Following what we have on Figma:
=> [BREAKING] Updating spacing tokens

packages/yoga/src/Input/web/Password.jsx, packages/yoga/src/Input/web/Password.test.jsx
Simple fix, where the component is focused if there is a href first
=> fix(password): fixing focus input for safari 

packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
This PR fixes:
- The style to truncate the list and button texts from the `PlanCard` component;
- Use the value from `subtitle` prop to display the correct value.
=> PlanCard: fix text truncate and subtitle prop

packages/yoga/src/TextArea/web/TextArea.jsx
This will fix the tests failing in CI.
=> Change fieldset import case

.github/workflows/npmpublish.yml
=> ci(debug): running ls

packages/doc/content/guidelines/tokens/breakpoints.mdx, packages/doc/src/components/Tokens/Tokens.jsx
This PR adds the missing docs for breakpoints tokens
=> Docs for breakpoints

packages/doc/src/components/CodeBlock/CodeBlock.jsx
There was missing the `peerDependencies` to make Snack work as expected.
Now it is working:
=> Add peerDependencies to Snack embed

packages/yoga/src/Button/web/Button.test.jsx, packages/yoga/src/Dropdown/native/Backdrop.jsx, packages/yoga/src/Dropdown/native/Options.android.jsx, packages/yoga/src/Dropdown/native/Options.ios.jsx
We are having problems importing the package on the generated bundle, this PR solves this issue.
=> fix: use relative import

packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/Input.test.jsx, packages/yoga/src/Input/native/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/Helper.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Input.test.jsx, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap
I added `hideMaxLength` prop in `<Helper/>`, because we need to hide the maxLegnth count into `<Input/>`. It’s unnecessary to presents this info to user in SingUp scenario (when user insert your national document, specifically in second step on the flow).
=> hide maxLength on Input

README.md
=> docs: add yoga-helpers to readme

packages/tokens/src/global/colors.js, packages/yoga/src/Theme/theme/theme.js
=> feat(colors): add feedback colors

packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/Input.test.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Input.test.jsx
Remove on change listener inside input component.
=> Update state management input

packages/yoga/src/Icon/Icon.jsx
Fixed our secondary main color name in the icon wrapper documentation
=> Fix color name - Icon Wrapper

packages/doc/content/components/components/text/default-native.mdx, packages/doc/content/components/components/text/default-web.mdx, packages/doc/content/components/components/text/index.mdx, packages/labnative/pages/Text.jsx, packages/yoga/src/Text/Text.theme.js, packages/yoga/src/Text/index.js, packages/yoga/src/Text/index.native.js, packages/yoga/src/Text/native/Text.jsx, packages/yoga/src/Text/native/Text.test.jsx, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/native/index.js, packages/yoga/src/Text/textStyle.android.jsx, packages/yoga/src/Text/textStyle.jsx, packages/yoga/src/Text/web/Text.jsx, packages/yoga/src/Text/web/Text.test.jsx, packages/yoga/src/Text/web/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/web/index.js
This add `SectionTitle` and `SmallestException` as a new variation to the text component
=> Add new variations to the text component

packages/doc/content/components/components/card/plancard-native.mdx, packages/doc/content/components/components/card/plancard-web.mdx, packages/labnative/pages/Card.jsx, packages/yoga/src/Card/Card.theme.js, packages/yoga/src/Card/native/Card/Actions.jsx, packages/yoga/src/Card/native/PlanCard/Actions.jsx, packages/yoga/src/Card/native/PlanCard/Content.jsx, packages/yoga/src/Card/native/PlanCard/List.jsx, packages/yoga/src/Card/native/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/native/PlanCard/Tag.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/index.js, packages/yoga/src/Card/web/Card/Actions.jsx, packages/yoga/src/Card/web/PlanCard/Actions.jsx, packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/web/PlanCard/Tag.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/index.js
- Update the PlanCard component to the new design. [Figma](https://www.figma.com/file/yuEFY338mVNHudQK3JX5Z3/%5BPixel%5D-Upgrade%2FDowngrade?node-id=6024%3A23394)
- Fix when the `buttonProps` (`PlanCard.ListItem`) does not exist and it renders a zero value.
| web | ios | android |
|:--- |:--- |:---     |
|<img width="220" src="https://user-images.githubusercontent.com/12848917/113925155-10b96580-97c1-11eb-8920-1ac82c97e8ff.png" />|<img width="220" src="https://user-images.githubusercontent.com/12848917/113925152-0f883880-97c1-11eb-8d61-36c9414a51a3.png" />|<img width="220" src="https://user-images.githubusercontent.com/12848917/113925157-1151fc00-97c1-11eb-8e43-9f48797d94e9.png" />|
=> Update the PlanCard component to the new design

packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
|--------|-----|
| ![image](https://user-images.githubusercontent.com/6536985/117199983-430ab280-adc1-11eb-8386-e25175d395d1.png)  | ![image](https://user-images.githubusercontent.com/6536985/117200035-5289fb80-adc1-11eb-9aad-9bf48e2ff447.png) |
** _Only web_
=> Duplicated margin right on icon

packages/yoga/src/Text/Text.theme.js, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/sharedTextStyle.jsx, packages/yoga/src/Text/web/__snapshots__/Text.test.jsx.snap
Text.Section should have a letter-spacing of 1px, which was applied in this change.
=> Add `letter-spacing` to Text.Section

README.md, packages/doc/content/components/components/box/box-native.mdx, packages/doc/content/components/components/box/box-web.mdx, packages/doc/content/components/components/box/index.mdx, packages/doc/content/system/getting-started/index.mdx, packages/doc/src/components/Layout/Layout.jsx, packages/labnative/pages/Box.jsx, packages/labnative/pages/index.js, packages/yoga/src/Box/index.js, packages/yoga/src/Box/index.native.js, packages/yoga/src/Box/native/Box.jsx, packages/yoga/src/Box/native/Box.test.jsx, packages/yoga/src/Box/native/__snapshots__/Box.test.jsx.snap, packages/yoga/src/Box/native/index.js, packages/yoga/src/Box/web/Box.jsx, packages/yoga/src/Box/web/Box.test.jsx, packages/yoga/src/Box/web/__snapshots__/Box.test.jsx.snap, packages/yoga/src/Box/web/index.js, packages/yoga/src/index.js, packages/yoga/src/index.native.js
| Web | Native  |
| -----| ------- |
|  ![image](https://user-images.githubusercontent.com/6536985/122226765-a7bf2f80-ce8c-11eb-9997-0b7582aad7ec.png) | ![image](https://user-images.githubusercontent.com/6536985/122226997-df2ddc00-ce8c-11eb-8b3e-aefe62cc53b0.png) | 
```jsx 
import { Box } from '@gympass/yoga';
<Box
border="small"
padding="small"
borderRadius="small"
color="feedback.success.dark"
>
Making wellbeing universal
</Box>
``` 
```jsx 
import { Box, Text } from '@gympass/yoga';
<Box
b="small"
p="small"
borderRadius="small"
color="feedback.success.dark"
as={Text}
>
Making wellbeing universal
</Box>
```
=> New component Box

packages/doc/content/components/components/card/plancard-native.mdx, packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/native/PlanCard/List.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[jira-task]: https://gympass.atlassian.net/browse/CODEME-184
[jira-img]: https://img.shields.io/badge/issue-JIRA-blue.svg
<center>
[![JIRA][jira-img]][jira-task]
</center>
| before | after |
|------- |------| 
| ![image](https://user-images.githubusercontent.com/46993493/129949580-90638c1f-b35a-4015-860c-78c177c83853.png) | ![image](https://user-images.githubusercontent.com/46993493/129949472-fd222d18-5fcb-4a30-9ba2-53cd87046787.png)  |
=> ✨  Change Icon color inside PlanCard

packages/yoga/src/Button/web/Outline.jsx
=> docs: update outline button proptypes

packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Card/native/EventCard/EventCard.jsx, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap
-  Fix `small` font size value on Button theme.
|   <img width="191" alt="Screen Shot 2021-08-23 at 10 56 13" src="https://user-images.githubusercontent.com/18318587/130460021-dc06616a-ac26-4162-985f-6952609d1465.png"> |    <img width="187" alt="Screen Shot 2021-08-23 at 10 55 54" src="https://user-images.githubusercontent.com/18318587/130460052-60c23e6a-e1eb-4903-ace6-d0416666ba9a.png">   |
=> [ENJ-288] - Adjust Button small prop fontsize

package.json, packages/yoga/src/Avatar/native/Avatar.jsx, yarn.lock
Fixing this
and [this](https://github.com/Gympass/yoga/runs/3461792202?check_suite_focus=true)
🚀 
cc/ @andreloureiro
=> Updating Avatar and fixing `sharp` version 

packages/doc/content/components/components/button/default-web.mdx, packages/doc/content/components/components/button/link-web.mdx, packages/doc/content/components/components/button/outline.mdx, packages/doc/content/components/components/button/text-web.mdx, packages/doc/content/components/components/list/list-web.mdx, packages/doc/content/components/components/progress/progress-web.mdx, packages/doc/content/components/components/rating/rating-web.mdx, packages/doc/content/components/components/snackbar/index.mdx, packages/doc/content/components/components/stepper/stepper-web.mdx, packages/doc/content/components/components/tag/default-web.mdx, packages/doc/content/components/components/text/default-web.mdx
Added the Box component, in the code examples in the component documentation
=> Refactor docs on components

.all-contributorsrc, README.md
Adjusting contributors badge on readme.md to be updated correctly
How the problem was solved:
https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update
=> fix: badge all contributors on readme should updated automatically

packages/labnative/pages/Result.jsx, packages/yoga/src/Result/native/Attendances.jsx, packages/yoga/src/Result/native/Details.jsx, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
- change default text size to 12px
- change icon size to 12px 
- change icon and text size to 12px
- change icon color to "deep"
| <img alt="ios screenshot" src="https://user-images.githubusercontent.com/7108030/132258349-93af5703-428b-466d-a739-a784d52d085e.png" width="300" /> |  <img alt="ios screenshot" src="https://user-images.githubusercontent.com/7108030/132258343-6b4a73b9-e758-4492-ae94-f183ca3812bd.png" width="300" />      |
=> Add layout adjustments to Result

packages/yoga/src/Result/native/Attendances.jsx, packages/yoga/src/Result/native/Details.jsx, packages/yoga/src/Result/native/TinyTextIcon.jsx, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
|     <img width="300px" src="https://user-images.githubusercontent.com/7108030/133332374-53b90f55-45ab-4470-96a2-17ac618ca375.png" />   |   <img width="300px" src="https://user-images.githubusercontent.com/7108030/133332691-3ace44dd-1116-4217-a1ae-ac1aee68864f.png" /> |
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/133332355-f0cdd739-6d54-41c3-9527-0a6432fb0c50.png" />    |    <img width="300px" src="https://user-images.githubusercontent.com/7108030/133332775-8efa176e-5268-41d2-bea8-558fe87e146e.png" />   |
=> Fix Result align on android devices

packages/doc/content/components/components/text/default-native.mdx, packages/doc/content/components/components/text/default-web.mdx
`variant` property of `Text` has been deprecated. Use `color` system prop instead.
**native**:
**web**:
}
**native**:
**web**:
}
=> docs(text): update prop variant to color

packages/doc/content/system/system/layout.mdx, packages/system/src/layout.js, packages/system/src/layout.test.js
Adding the follow new props to `@gympass/system`:
- `zIndex`
=> ✨ Add new prop zIndex to system

packages/yoga/src/Dialog/web/Dialog.jsx
The reason for this PR is to solve a problem that is generating when running the tests in CI
Problem: [Github Actions](https://github.com/Gympass/yoga/runs/4170001262?check_suite_focus=true)
I believe the problem is solved with this:
[Issue](https://github.com/reactjs/react-docgen/issues/336#issuecomment-820406306)
I already had this problem during this development and the @ggdaltoso  indicated this issue
=> Fix problem on Dialog

.github/workflows/main.yml
This adds a new job to run for pushes and pull requests in order to validate the code by running our linters and tests instead of running it only after the code goes to our master branch.
=> feat(gh-actions): add new code validation job

.github/workflows/main.yml
Remove `branches-ignore` which isn't needed for pull_request event
=> fix(main-workflow): remove uneeded config

packages/doc/content/components/getting-started/default-native.mdx
- Add peer dependencies section for React Native's getting started section
New section:
=> feat(doc-native): add peer dependencies section

packages/doc/content/components/icons/icons-web.mdx
=> docs(icons): fix typo in icons-web.mdx

packages/yoga/src/Result/native/Details.jsx, packages/yoga/src/Result/native/Result.test.jsx, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
When using this component without passing anything in the limitLabel property the text undefined was
showing and this PR fixes this problem. Also removed the padding 0 from the numberOfItemsLeft property. 
| Before |  After | 
| ------ | ------ | 
|    ![image](https://user-images.githubusercontent.com/44280864/142273310-a8a3efb2-7896-450a-9ac3-3d522f461ab7.png)    |        ![image](https://user-images.githubusercontent.com/44280864/142272215-c47f2c51-e716-4b1d-b75f-75c9abada378.png)    |
=> Change the limitLabel defaultProps and remove the 0 from numberOfItemsLeft property

packages/doc/content/components/components/divider/divider-native.mdx, packages/doc/content/components/components/divider/divider-web.mdx, packages/doc/content/components/components/divider/index.mdx, packages/labnative/pages/Divider.jsx, packages/labnative/pages/index.js, packages/yoga/src/Divider/Divider.theme.js, packages/yoga/src/Divider/index.js, packages/yoga/src/Divider/index.native.js, packages/yoga/src/Divider/native/Divider.jsx, packages/yoga/src/Divider/native/Divider.test.jsx, packages/yoga/src/Divider/native/__snapshots__/Divider.test.jsx.snap, packages/yoga/src/Divider/native/index.js, packages/yoga/src/Divider/web/Divider.jsx, packages/yoga/src/Divider/web/Divider.test.jsx, packages/yoga/src/Divider/web/__snapshots__/Divider.test.jsx.snap, packages/yoga/src/Divider/web/index.js, packages/yoga/src/index.js, packages/yoga/src/index.native.js
The Divider component can be used to divide two parts of another component or to separate parts of
screen.
| WEB | APP |
| ----- | ----- |
|![Captura de Tela 2021-11-25 às 10 14 35](https://user-images.githubusercontent.com/94182676/143448124-1646db41-66a6-4e57-9e44-bc8fcbfefbb5.png)|![Simulator Screen Shot - iPhone 11 - 2021-11-25 at 09 51 04](https://user-images.githubusercontent.com/94182676/143447812-3423955e-d72b-44ab-8195-a3fb7df48d3a.png)
=> feat(component): a Divider component to separate two parts of another component

packages/doc/content/components/components/card/plancard-native.mdx, packages/labnative/pages/Card.jsx, packages/yoga/src/Card/native/PlanCard/Content.jsx, packages/yoga/src/Card/native/PlanCard/List.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap
Changed the PlanCard design to new layout with the Price and Title in same size and with the possibility of change the ListItem color.
[JIRA](https://gympass.atlassian.net/browse/ENJ-388)
[ FIGMA](https://www.figma.com/file/WI7iB8gTsIrY4WhWybpDwN/%5BHercules%5D-Product-Restrictions?node-id=3408%3A113709)
| ------| -------| 
|![Captura de Tela 2021-11-25 às 09 36 27](https://user-images.githubusercontent.com/94182676/143443334-36a9447b-98a8-471f-9b38-4e49ddc98ad9.png) |![Captura de Tela 2021-11-25 às 09 38 37](https://user-images.githubusercontent.com/94182676/143443428-c0f107c2-0f18-4efb-b9a4-f896ffc1b39b.png)
=> feat(component): changed the design of App PlanCard to new layout

packages/labnative/pages/Card.jsx, packages/yoga/src/Card/Card.native.theme.js, packages/yoga/src/Card/Card.theme.js, packages/yoga/src/Card/Card.web.theme.js, packages/yoga/src/Card/native/PlanCard/Actions.jsx, packages/yoga/src/Card/native/PlanCard/Content.jsx, packages/yoga/src/Card/native/PlanCard/List.jsx, packages/yoga/src/Card/native/PlanCard/PlanCard.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/Actions.jsx, packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Divider/native/__snapshots__/Divider.test.jsx.snap
I adjusted the spacings on native Plan Card to be equal to the Figma project, and I kept the web
style the same was.
[JIRA](https://gympass.atlassian.net/browse/ENJ-460)
[FIGMA](https://www.figma.com/file/WI7iB8gTsIrY4WhWybpDwN/%5BHercules%5D-Product-Restrictions?node-id=4683%3A121501)
| ----- | ----- |
| ![Captura de Tela 2021-12-07 às 11 04 13](https://user-images.githubusercontent.com/94182676/145044826-426f9fbc-991c-4955-92b7-8696333989d7.png) | ![Captura de Tela 2021-12-07 às 11 02 16](https://user-images.githubusercontent.com/94182676/145043464-0da55c05-3d6b-450c-9ca3-056e67371ef5.png)
=> refactor(component): adjusted the spacings on native Plan Card

packages/yoga/src/Header/web/Header.jsx
Fixing the wrong path of Header's image
=> fix(header): fix image path

packages/doc/src/components/Clipboard/index.jsx, packages/doc/src/components/CodeBlock/PrismHighlight/PrismHighlight.jsx, packages/doc/src/components/CodeBlock/ReactLive/ReactLive.jsx
https://user-images.githubusercontent.com/39073602/153646711-2feabaf1-c1ab-471f-930d-dae359c0097b.mov
- Facility to copy some text to test
- create new component to copy text
=> ✨ Clipboard

.github/workflows/npmpublish.yml
=> Update secret key npm

scripts/publish
=> Update script to lerna

packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/CodeBlock/shared/modules/index.js, packages/doc/src/components/CodeBlock/shared/modules/modules.js
=> :hammer: Fix system documentation in codeSandBox

examples/with-next/README.md, packages/doc/src/components/CodeBlock/shared/templates/native.js
Add font loader to native documentation and next example to docs
|![image](https://user-images.githubusercontent.com/46993493/165315430-b76ef1ab-2c66-4208-bbd5-bbf2441b9454.png)|![image](https://user-images.githubusercontent.com/46993493/165315797-b5950483-68e0-463c-87ee-f4f5886202b2.png)|
=> 🚀  Add font loader and next example to docs

packages/yoga/src/Theme/index.native.js, packages/yoga/src/index.native.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/CUP-27)
Today, the function `createTheme` is only provided to the `Web` version of the Yoga. 
This PR adds the possibility to change the `Mobile` as well to make compatible the functionalities and fit the colors changes that the Wellz app will go to require.
Go to the NativeLab and change the theme. 
N/A
=> [CUP-27] - Add createTheme to Native version 🚀 

packages/doc/content/components/components/header/index.mdx, packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Header/web/Header.jsx, packages/yoga/src/Header/web/Header.test.jsx, packages/yoga/src/Header/web/Logo.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/MAR-2862?atlOrigin=eyJpIjoiNzk0MjZiNjE4NDkzNDE3ZDlkNGYwNDFmYTExNDIzZDgiLCJwIjoiaiJ9)
On Jun 1, we will release a campaign that changes the Gympass logo to a Pride logo version. This contribution to Header's component is to pass a component via prop so it makes it possible to add a custom logo.
- Created logo prop in Header component, if passed will show the custom logo otherwise the default logo will be shown.
- We need to pass a Markdown component into the label prop, so the node prop was added to the label prop types to stop returning a prop error in the console. 
=> feat(header): add a prop in headers to change the logo to a custom

.all-contributorsrc, README.md
Add @diegomarcuz as a contributor for bug
=> docs: add diegomarcuz as a contributor for bug

packages/yoga/src/Card/native/PlanCard/Actions.jsx, packages/yoga/src/Card/web/PlanCard/Actions.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1729)
Use default `size` for both buttons, the `ButtonText` was using a different `size`.
- x ] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
|   <img src="https://user-images.githubusercontent.com/7108030/174295414-0b23d32b-8489-4417-a6d8-a1a1350da491.png" width="300px"/>     |    <img src="https://user-images.githubusercontent.com/7108030/174295396-d65afcbc-1629-468f-8a58-73075ab4294e.png" width="300px"/>    |
=> 🚀 Use default size for PlanCard buttons

packages/yoga/src/Heading/web/BackButton.jsx, packages/yoga/src/Heading/web/Heading.jsx, packages/yoga/src/Heading/web/RightButton.jsx, packages/yoga/src/Heading/web/Title.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1736)
Add displayName to Heading components.
The Heading components where not being rendered is production mode because the name where being changed.
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/174628623-613b19fc-2fa2-4bf3-96e5-9abf3365750a.png"/>    |    <img width="300px" src="https://user-images.githubusercontent.com/7108030/174628612-116923fe-6875-4f9c-86b8-458c44200fd5.png"/>   |
=> 🐞 Heading components is not being rendered in production mode

packages/yoga/src/Heading/Heading.theme.js, packages/yoga/src/Heading/web/BackButton.jsx, packages/yoga/src/Heading/web/Heading.jsx, packages/yoga/src/Heading/web/RightButton.jsx, packages/yoga/src/Heading/web/StyledHeading.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1765)
This PR adjust some stylization params to match figma prototype for the heading component and allow the component to receive children as optional.
|    <img src="https://user-images.githubusercontent.com/44280864/176764519-756fca18-aeda-4ef3-a97f-130fee8b326d.png" width="320px" />   |    <img src="https://user-images.githubusercontent.com/44280864/176764295-1d5108d1-2df3-42cc-82c5-657939123362.png" width="320px" />   |
|    <img src="https://user-images.githubusercontent.com/44280864/176765046-717c1d45-e69e-4c0c-98a5-651db520c8d5.png" width="320px" />   |    <img …
=> Update heading height to match figma 🚀

packages/doc/content/components/illustrations/illustrations-native.mdx, packages/doc/content/components/illustrations/illustrations-web.mdx, packages/illustrations/readme.md, packages/illustrations/src/index.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-403)
We need to add the 12 2D illustrations we currently have on Yoga Figma to the Yoga development side. To achieve this goal, as we talked, a new `@gympass/yoga-illustration` was created, which contains all the illustrations requested in the task.
This PR is a fix for the #511 
It was aligned that both icons and illustrations do not have tests.
=> [DS-403] Add 2D Illustrations to Yoga 🚀

packages/labnative/metro.config.js
Add the `@gympass/yoga-illustrations` to metro configuration in `libnative`.
=> fix(libnative): add illustrations to metro configuration 🐞

packages/yoga/package.json
We need to add the `@gympass/yoga-illustrations` as a dependency of the `@gympass/yoga` to make the doc's examples works.
=> 🐞 Add @gympass/yoga-illustrations to Yoga dependencies.

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/Card.native.theme.js, packages/yoga/src/Card/Card.theme.js, packages/yoga/src/Card/Card.web.theme.js, packages/yoga/src/Card/native/PlanCard/Content.jsx, packages/yoga/src/Card/native/PlanCard/PlanCard.jsx, packages/yoga/src/Card/native/PlanCard/Tag.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/Tag.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1868)
- Adjust spacings to match prototype.
- Replace box shadow with border.
- Align list items
- Keep action at card bottom.
Web
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/180833872-1a182aab-2e76-4c58-ba48-107492e58191.png" />    |    <img width="300px" src="https://user-images.githubusercontent.com/7108030/180833845-11315df6-b8e5-4a27-8f61-4349b7ee8740.png" />   |
IOS
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/180836285-c41abb0a-5ddf-4a47-884f-a6ed4eb1272c.png" />    |    <img width="300px" …
=> 🚀 Update PlanCard styles

packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2002)
Decrease height from `PlanCard` component removing the margin bottom from last list item. 
|    <img width="300px"  src="https://user-images.githubusercontent.com/7108030/181285638-ad8af030-72e3-42bd-9605-614b136aae5f.png" />  |    <img width="300px"  src="https://user-images.githubusercontent.com/7108030/181285716-8afb14d0-0ce4-4b50-8562-a07faa26f424.png" />   |
=> 🚀 Decrease PlanCard height

packages/doc/src/components/Documentation/Documentation.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-github-blue.svg)](https://github.com/gympass/yoga/issues/517)
| Doc's preview | Rendered illustration  |
| ![Captura de Tela 2022-07-20 às 12 00 20](https://user-images.githubusercontent.com/25802240/180015027-1fd543b9-ae98-452a-963f-ea5fcd35a63d.png) |   TODO    |
=> [#517] Error when trying to import illustration from yoga-illustrations 🐞

packages/illustrations/readme.md, packages/illustrations/src/index.js
=> chore: only change import order

packages/illustrations/src/index.js, scripts/prepublish.js
=> feat: add try catch

packages/illustrations/src/index.js, scripts/publish
=> feat: add new log level

packages/illustrations/src/index.js, scripts/prepublish.js
=> feat: add log

packages/doc/content/components/components/bottomsheet/index.mdx, packages/yoga/src/BottomSheet/web/BottomSheet.jsx, packages/yoga/src/BottomSheet/web/BottomSheet.test.jsx, packages/yoga/src/Dialog/web/Dialog.jsx, packages/yoga/src/Dialog/web/Dialog.test.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1990)
When using the `onClose` prop in `BottomSheet`, a close button is displayed, this button should be hidden as default.
- **Dialog**: add prop `hideCloseButton` to hide the close button when the `onClose` prop is defined
- **BottomSheet**: hide the close button as default
|    <img src="https://user-images.githubusercontent.com/7108030/182829954-90211d3c-a61c-4b3a-a2ee-8e5bf4cc190f.png" width="300px">    |    <img src="https://user-images.githubusercontent.com/7108030/182829992-7c9e86ee-7109-4c2e-9297-9f590b19df92.png" width="300px">   |
https://user-images.githubusercontent.com/7108030/182828646-d9c2b016-31ab-407e-b7e4-1cae9fe1964b.mov
=> 🚀 Hide the close button from BottomSheet

packages/doc/content/components/components/menu/index.mdx, packages/yoga/src/Menu/web/MenuList.jsx
In order to `<Menu />` be more flexible we are adding props to add placement options
|<img src="https://user-images.githubusercontent.com/6570553/183135385-0b3f8a14-55e7-4255-b29e-44d0d3cce65e.png" />| <img src="https://user-images.githubusercontent.com/6570553/183135224-f4ef50ab-d15f-402c-8715-361499ccf2f7.png" />|
=> ✨ Add menu placement

packages/doc/content/components/components/skeleton/index.mdx, packages/doc/content/components/components/skeleton/skeleton-native.mdx, packages/doc/content/components/components/skeleton/skeleton-web.mdx, packages/labnative/pages/Skeleton.jsx, packages/labnative/pages/index.js, packages/yoga/src/Skeleton/Skeleton.theme.js, packages/yoga/src/Skeleton/index.js, packages/yoga/src/Skeleton/index.native.js, packages/yoga/src/Skeleton/native/Skeleton.jsx, packages/yoga/src/Skeleton/native/Skeleton.test.jsx, packages/yoga/src/Skeleton/native/__snapshots__/Skeleton.test.jsx.snap, packages/yoga/src/Skeleton/native/index.js, packages/yoga/src/Skeleton/web/Skeleton.jsx, packages/yoga/src/Skeleton/web/Skeleton.test.jsx, packages/yoga/src/Skeleton/web/__snapshots__/Skeleton.test.jsx.snap, packages/yoga/src/Skeleton/web/index.js, packages/yoga/src/index.js, packages/yoga/src/index.native.js
This PR adds a new component called `Skeleton`, used to hold placing the layout while the data is being loaded.
https://user-images.githubusercontent.com/25802240/182608606-bfe7c7b2-9316-4dea-a7f3-c3d410ea569b.mp4
https://user-images.githubusercontent.com/25802240/182608515-1f58eed8-bc20-471c-9dce-f2fa86dfb2c4.mp4
=> 🚀 Add Skeleton component

packages/yoga/package.json
This PR update a version of package illustration! 
This change makes yoga look at the latest published version of the illustrations! Before it was looking at a non-existent version
=> fix(illustration): change version of package

scripts/notify.js
Since we are migrating from Slack to Google Chats, this PR adapts the logic to notify on the `ds-release` channel in Google Chats.
|    <img width="508" alt="Captura de Tela 2022-08-09 às 11 04 18" src="https://user-images.githubusercontent.com/25802240/183669592-d9073a91-ca01-4a42-84ad-e297aed1d9a0.png">|    <img width="529" alt="Captura de Tela 2022-08-09 às 11 04 54" src="https://user-images.githubusercontent.com/25802240/183669736-545259c9-7451-415a-b38d-047574a751cd.png">   |
=> 💣 Move notify bot to Google Chats channel

package.json, packages/yoga/package.json
=> fix(datepicker): correctly a moment on package datepicker

packages/doc/content/components/components/heading/index.mdx, packages/yoga/src/Heading/web/Heading.jsx, packages/yoga/src/Heading/web/Heading.test.jsx, packages/yoga/src/Heading/web/StyledHeading.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/jira/software/c/projects/AC/boards/180?modal=detail&selectedIssue=AC-3636)
Related initial task
- Added a new prop to `Heading` component to remove padding when needed.
=> fix(heading): add new prop to remove padding

packages/yoga/src/Datepicker/web/Datepicker.test.jsx, packages/yoga/src/Skeleton/native/Skeleton.test.jsx, packages/yoga/src/Skeleton/native/__snapshots__/Skeleton.test.jsx.snap
The CI is failing at the tests step. This is caused by a broken test inside the `Date Picker` component, where expect that the result of the test execution matches the snapshot.
The problem is that the snapshot was created with a specific month, and because of that, all the others months will fail. To solve the problem, a simple mock was added to this single test to force the `Date` to be the same as expected in the snapshot.
This PR also adds a missing required prop to the `Skeleton` component that was throwing an error.
=> 🐞 Fix broken tests in CI

packages/labnative/package.json, packages/yoga/src/Card/native/GymCard/CheckIn/CheckIn.jsx
Adding new library to fix problem on react native 0.70.1
=> refactor(install new lib): adding new library to fix problem on react native 0.70.1 🚀 

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirementStyles.js, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/jira/software/c/projects/AC/boards/180?modal=detail&selectedIssue=AC-3735)
- Fix desktop and mobile layout structure
- Review and fix spacing of elements
Check the Yoga component's Handoff: [figma](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/%E2%9C%85-Yoga-%5BMAIN%5D?node-id=30899%3A261593)
|     <img width="687" alt="Screen Shot 2022-10-03 at 17 38 50" src="https://user-images.githubusercontent.com/27781419/193678019-7c143aa0-49ce-4ede-a4ad-701473b87749.png">   |    <img width="689" alt="Screen Shot 2022-10-03 at 17 39 17" src="https://user-images.githubusercontent.com/27781419/193678136- …
=> ActionRequirement - Fix/adjust position illustration and specs 🐞

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
set width content wrapper
|     <img width="1920" alt="Screen Shot 2022-10-04 at 11 44 48" src="https://user-images.githubusercontent.com/27781419/193851819-0b1f8e0d-52dd-42d2-ada5-9230abdf1605.png">   |    <img width="1920" alt="Screen Shot 2022-10-04 at 11 44 34" src="https://user-images.githubusercontent.com/27781419/193851984-202c3dfb-7746-4be7-8f65-31e748d33f43.png">   |
=> set width content wrapper

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
Fix/reset width content on mobile
=> ActionRequirement - Fix/reset width content on mobile

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
=> fix: adjust desktop

packages/yoga/src/ActionRequirement/native/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirement.test.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap, yarn.lock
In this PR I fixed a bug that I noticed when I'm using the `ActionRequirement` component without passing value for the `list` prop. When the `ActionRequirement` component is used passing the `list` prop or without using this prop, a paragraph element is rendered anyway leaving an empty space.
=> 🐞 Fix: Remove empty paragraph if is not needed on ActionRequirement

packages/doc/content/components/components/tag/informative-native.mdx, packages/yoga/src/Tag/native/Informative.jsx, packages/yoga/src/Tag/native/Tag.test.jsx, packages/yoga/src/Tag/native/__snapshots__/Tag.test.jsx.snap
…types[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ENG-4129)
When the informative tag's `neutral` variant was implemented the native prop type validation was not updated, this PR is just to update it and add it to the native doc, and tests.
Execute the project and check if the neutral variant usage at `Tag.Informative` is still throwing a warning console message.
`Not applicable`
=> [ENG-4129] - Add neutral variant at native Tag.informative prop types 🚀

packages/yoga/src/Datepicker/web/Datepicker.jsx, packages/yoga/src/Datepicker/web/Datepicker.test.jsx, packages/yoga/src/Datepicker/web/__snapshots__/Datepicker.test.jsx.snap, yarn.lock
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/TVM-604)
Display UTC dates so that everyone gets the same date regardless of the timezone their in.
=> 🚀 Datepicker - display UTC dates

packages/yoga/src/Skeleton/Skeleton.theme.js, packages/yoga/src/Skeleton/native/Skeleton.jsx, packages/yoga/src/Skeleton/native/Skeleton.test.jsx, packages/yoga/src/Skeleton/native/__snapshots__/Skeleton.test.jsx.snap, packages/yoga/src/Skeleton/web/Skeleton.jsx, packages/yoga/src/Skeleton/web/Skeleton.test.jsx, packages/yoga/src/Skeleton/web/__snapshots__/Skeleton.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ENG-4159)
While we were implementing the Shimmer from a screen the yoga Skeleton component was throwing some prop validation errors, to fix it and add margins to the component to make easier screens implementation is necessary to update the Skeleton component at the Yoga.
Run the project and check if the Skeleton component is still showing as expected.
=> [ENG-4159] - Update Skeleton text variant usage and add yoga system to the component 🚀

packages/yoga/src/Skeleton/native/Skeleton.jsx, packages/yoga/src/Skeleton/native/__snapshots__/Skeleton.test.jsx.snap, packages/yoga/src/Skeleton/web/Skeleton.jsx, packages/yoga/src/Skeleton/web/__snapshots__/Skeleton.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ENG-4162)
Using the [Skeleton](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Skeleton/Skeleton.js) from MaterialUI as a reference I updated the Yoga Skeleton animation.
- Check the Skeleton at the doc and at the native emulators.
| Web | iOS |
| ![Web - Screen Recording](https://user-images.githubusercontent.com/5889973/196744892-afc6ad75-320b-40ea-b5a2-e5b8696cc6c4.gif) | ![iOS - Screen Recording](https://user-images.githubusercontent.com/5889973/196744901-773dba9a-05b8-48d1-8218-c9b820178061.gif) |
=> 🚀 Fix Skeleton animation

packages/yoga/package.json, packages/yoga/src/Menu/web/MenuList.jsx, packages/yoga/src/Menu/web/__snapshots__/Menu.test.jsx.snap, yarn.lock
Fix in Menu Component and update a Radix-ui menu package
=> Ds 474 dropdown menu fix

package.json, packages/yoga/src/Menu/web/MenuItem.jsx
The main idea of this PR is to be able to add color and size to an Icon inside the Menu Item component. As of now we have the default values set to:
```
colors: #9898A6
size: 20px
```
Before:
```
<Box display="flex" flexDirection="column" alignItems="center">
<Menu onHover>
<Menu.Action>
<Button.Icon icon={Home} />
</Menu.Action>
<Menu.List align="end">
<Menu.Item icon={Refresh} fill="#D8385E"><Text>Olá</Text></Menu.Item>
</Menu.List>
</Menu>
</Box>
```
After:
```
<Box display="flex" flexDirection="column" alignItems="center">
<Menu onHover>
<Menu.Action>
<Button.Icon icon={Home} />
</Menu.Action>
<Menu.List align="end"> …
```
=> 🚀  Add support for Icon color and size to MenuItem component

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2335)
- Add `extra` prop to render any component before the divider.
- Remove `Price` component when price prop doesn't exists.
- Tun `price` and `period` props to optional.
```js
<PlanCard>
<PlanCard.Content title="Basic" extra={<p>Free</p>} />
</PlanCard>
```
=> feat(PlanCard): add "extra" prop to PlanCard.Content 🚀

packages/yoga/src/Menu/web/Menu.jsx, packages/yoga/src/Menu/web/MenuList.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-500)
- Add extra prop to deal with Menu List elevation.
=> 🚀 add prop to deal with Menu elevation

packages/yoga/src/Menu/web/MenuList.jsx
Menu list bug fix - Missing ";"
=> 🐞 menu list css bug fix

packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-512)
The position of the subtitle was in the center, I adjusted it to be on the start position.
| <img width="327" alt="Screen Shot 2022-12-06 at 18 18 30" src="https://user-images.githubusercontent.com/32910717/206025322-530687e9-87f7-4821-a1c8-0b0877e3b2d7.png"> | <img width="327" alt="Screen Shot 2022-12-06 at 18 18 42" src="https://user-images.githubusercontent.com/32910717/206025388-b63809aa-0430-43e4-91dc-38a054069131.png"> |
=> 🐞 fix(components): adjust subtitle accordion position

packages/doc/content/components/components/button/link-web.mdx, packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/web/Button.test.jsx, packages/yoga/src/Button/web/Link.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-515)
Added the `icon` prop to `Button.Link` variation
|  <img width="1190" alt="image" src="https://user-images.githubusercontent.com/15070719/207397411-5b355955-81ae-4095-adce-e43e4fcb9feb.png"> | <img width="1190" alt="image" src="https://user-images.githubusercontent.com/15070719/207398013-0be241bc-131a-464f-a72b-47409a73ece7.png"> |
=> 🚀 feat(link button): add icon prop to link button

packages/yoga/src/Accordion/Accordion.theme.js, packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/jira/software/c/projects/DS/boards/558?modal=detail&selectedIssue=DS-513)
I adjusted the title font-weight to 500
| <img width="897" alt="Screen Shot 2022-12-07 at 16 17 38" src="https://user-images.githubusercontent.com/32910717/206275251-3430a6a7-eb1e-42ec-9d03-b9e0636d5f96.png"> | <img width="895" alt="Screen Shot 2022-12-07 at 16 17 48" src="https://user-images.githubusercontent.com/32910717/206275339-d5183672-db21-4796-9d4d-18d205621726.png"> |
=> 🐞 fix(components): adjust title font-weight accordion

packages/doc/content/components/components/accordion/index.mdx, packages/yoga/src/Accordion/web/Accordion.jsx
Adding an expanded props so that it is possible to open Accordion by default
=> 🚀 Feat/add expanded props to accordion

.all-contributorsrc, README.md
I noticed that the contributions made by me were repeated because I changed my github user a while ago.
To solve it, I made some adjustments manually in the `.allcontributors` file and in the `readme`.
| <img width="714" alt="Screenshot 2023-01-09 at 13 03 52" src="https://user-images.githubusercontent.com/32910717/211353543-a3292f1c-966a-49ab-bc19-b763554d502d.png"> | <img width="716" alt="Screenshot 2023-01-09 at 13 05 59" src="https://user-images.githubusercontent.com/32910717/211353731-50fce60a-285b-4094-a135-996ffb4ca65c.png"> |
=> 🚀chore(readme): adjust repeat user from all-contributors

README.md, packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap
[![PCODE-461](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PCODE-461)
In current behavior on activity sheets is being cut. in the correction, the text was centered so as not to cut.
[PCODE-461]: https://gympass.atlassian.net/browse/PCODE-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🐞 fix(chips): Activities pills text being cut

packages/doc/content/components/components/feedback/index.mdx, packages/yoga/src/Feedback/web/StyledFeedback.jsx
[Fix mobile view on Feedback Component]
[The PR dont need a new test]
|     
|   
|
=> fix(feedback): fix feedback mobile position and update documentation

packages/doc/content/components/components/feedback/index.mdx, packages/yoga/src/Feedback/web/Feedback.jsx, packages/yoga/src/Feedback/web/Feedback.test.jsx, packages/yoga/src/Feedback/web/__snapshots__/Feedback.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-550)
Add the `center` props to the `Feedback` component to allow the usage in a context where doesn't need to be vertically centered.
**Example of usage with additional content**
=> 🚀 feat(components): add center props to feedback component

packages/yoga/babel.config.js, packages/yoga/package.json, packages/yoga/src/Input/web/Phone.style.js, yarn.lock
Currently, we have a direct `css` import on `Phone.style.js`. That's needed for the component. However, when bundling the modules, we are forcing other projects to include a `css-loader` to build their bundle. Otherwise, they will erros such as the one bellow:
This PR fixes that by including a transform to handle those file imports and include them in the `js` bundle.
=> fix(components) 🚀 add css in js transform

packages/yoga/babel.config.js, packages/yoga/package.json, packages/yoga/src/Input/web/Phone.style.js, yarn.lock
**WHAT**
Reverts gympass/yoga#613
**WHY**
```
ERROR in ./node_modules/@gympass/yoga/esm/Input/web/Phone.style.js 273:0-22
Module not found: Error: Can't resolve 'load-styles' in '/Users/micaelrodrigues/Projects/partners-reports-mfe/node_modules/@gympass/yoga/esm/Input/web'
resolve 'load-styles' in '/Users/micaelrodrigues/Projects/partners-reports-mfe/node_modules/@gympass/yoga/esm/Input/web'
Parsed request is a module
```
Until we find a way to solve this.
=> Revert "fix(components) 🚀 add css in js transform"

packages/yoga/src/Input/web/Phone.style.js, packages/yoga/src/Input/web/__snapshots__/Phone.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-15)
Currently, we have a direct `css` import on `Phone.style.js`. Those are the base styles that come with [react-phone-input-2](https://github.com/bl00mber/react-phone-input-2). However, when bundling the modules, we are forcing other projects to include a `css-loader` to build their bundle. Otherwise, they will see errors such as the one bellow:
This PR removes that `css` import and integrates the base styles we need directly into the styled component.
=> fix(Phone):🐞 remove css import and integrate base styles

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2619)
- Decrease border size
- Add light style to border
- Add `badgeColor` prop to `PlanCard.Content` to add a colored badge to the title.
- Add `discount` prop to `PlanCard`.
```js
<PlanCard discount="SAVE 40%">
<PlanCard.Tag variant="informative">Active</PlanCard.Tag>
<PlanCard.Content
title="Gold"
currency="$"
price="99.90"
period="/mo"
badgeColor="energy"
>
<PlanCard.List>
<PlanCard.ListItem icon={Checkin} text="2.900 gyms and studios" />
<PlanCard.ListItem icon={Dumbbell} text="1x/day standard access" />
<PlanCard.ListItem icon={User} text="4x/month 1-on-1 sessions" />
</PlanCard.List>
</PlanCard.Content>
</PlanCard>
```
|   <img …
=> 🚀 feat(PlanCard): add discount and badgeColor props

packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2635)
Fix glitch with discount decoration when scrolling the card or zooming in.
|   <img src="https://user-images.githubusercontent.com/7108030/222799538-2fc55d18-63d0-42db-8646-3de1e2e71a3f.png" width="300px" />     |    <img src="https://user-images.githubusercontent.com/7108030/222799518-8f8bba80-6230-4ceb-8a15-c1587c1db99f.png" width="300px"/>   |
=> 🐞 fix(PlanCard): fix glitch with discount decoration

packages/doc/content/components/components/drawer/index.mdx, packages/yoga/src/BottomSheet/web/__snapshots__/BottomSheet.test.jsx.snap, packages/yoga/src/Dialog/web/Dialog.jsx, packages/yoga/src/Dialog/web/__snapshots__/Dialog.test.jsx.snap, packages/yoga/src/Drawer/web/Drawer.jsx, packages/yoga/src/Drawer/web/__snapshots__/Drawer.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-58)
This PR fixes a [stale closure](https://tkdodo.eu/blog/hooks-dependencies-and-stale-closures) on `closeDialog` and `keyPress` callbacks, which is preventing to close the drawer by clicking on the `Overlay` or by pressing `Esc` key **when the `onClose` prop is set**.
Additionally, i've also updated the `Drawer` `width` to be the minimum between the default (`600px`) and `100%`, so the drawer can adapt if the screen is smaller than that.
To test this, use the `Drawer` example, where i've added the `onClose` prop by default. Alternatively, you can change the props on `Dialog` examples.
https://user-images.githubusercontent.com/796443/223707675-550949fd-93f7-40cc-b652-7537e47f4f5b.mov …
=> fix(Dialog) fix stale closure on close actions

README.md, packages/doc/content/components/components/accordion/index.mdx, packages/yoga/src/Accordion/Accordion.theme.js, packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/Accordion.test.jsx, packages/yoga/src/Accordion/web/Small.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap, packages/yoga/src/Accordion/web/index.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-565)
(WHAT)
Create a small variation for accordion component, following some rules: 
1. 0px(spacing.zero) of padding left and right (that must be considered as a true or false alternative)
2. 16px(spacing.small) of padding top and bottom  
3. font size 14px using body 2 medium token (fontSizes.small) 
(WHY)
For use cases that require small spaces in padding, for example, a combination of a list and accordion in a drawer 
=> 🚀  (feat): new small accordion

packages/doc/content/system/system/typography.mdx, packages/system/src/typography.js, packages/system/src/typography.test.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-603)
I'm currently working on refactoring the drawer and needed to add some text that will always be uppercase, so I noticed that we don't have a text transform prop to use in the <Text> component, so I saw an opportunity to add this option for us to use.
=> 🚀 feat(typography): add text-transform

packages/doc/content/components/components/drawer/index.mdx, packages/doc/content/components/components/text/default-native.mdx, packages/doc/content/components/components/text/default-web.mdx, packages/labnative/pages/Text.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap, packages/yoga/src/ActionRequirement/native/__snapshots__/ActionRequirement.test.jsx.snap, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap, packages/yoga/src/Avatar/native/__snapshots__/Avatar.test.jsx.snap, packages/yoga/src/Box/native/__snapshots__/Box.test.jsx.snap, packages/yoga/src/Card/native/GymCard/CheckIn/__snapshots__/CheckIn.test.jsx.snap, packages/yoga/src/Card/web/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap, packages/yoga/src/Dropdown/native/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Feedback/web/__snapshots__/Feedback.test.jsx.snap, packages/yoga/src/Heading/web/Title.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap, packages/yoga/src/Snackbar/native/__snapshots__/Snackbar.test.jsx.snap, packages/yoga/src/Text/native/Text.jsx, packages/yoga/src/Text/native/Text.test.jsx, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/sharedTextStyle.jsx, packages/yoga/src/Text/web/Text.jsx, packages/yoga/src/Text/web/Text.test.jsx, packages/yoga/src/Text/web/__snapshots__/Text.test.jsx.snap
[![RTN-188](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/)
This PR add `fontSize` props to internal components that use Text component with `size` props. Anyone who use `size` props will have no problem.
| Text with `size` and `fontSize` props |
| ------ |
|![text](https://user-images.githubusercontent.com/127952311/227297611-a6186381-20b1-4905-a2f3-e162d33cc05b.gif)|
[RTN-188]: https://gympass.atlassian.net/browse/RTN-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ⚙️ refactor(Text): change props size to fontSize

packages/yoga/src/Dropdown/web/Dropdown.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/TVM-924)
- This PR is created to fix this opened issue #445 
- Brief issue description: if we send a new list of `options` to the `<Dropdown/>`component and that list contains a selected item, the component does not update accordingly. It updates the options list but not the selected item.
- [IMPORTANT‼️] Check the testing section, where I might need some assistance/guidance to fully test this bug fix
Alright, so I found it pretty hard to test this bug fix, manually. Ideally, one way to test this fix would be to create an `useEffect` and update the `options` prop that is passed to the component with a new selected item, then validate if the component updated accordingly. Not sure if …
=> 🐞 Dropdown fix - updating options dynamically

packages/yoga/src/Popover/web/Popover.jsx, packages/yoga/src/Popover/web/__snapshots__/Popover.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-74)
This PR updates the popover to make sure events are not bubbled to parent. Example: if you press the popover inside a `anchor`, you want to make sure the link is not opened and instead the popover is visible.
I've update the popover trigger to be a `button`. Here's why: https://www.builder.io/blog/buttons#the-problem-with-divs
I've also added [onTouchStart](https://www.w3schools.com/jsref/event_touchstart.asp) and [onTouchEnd](https://www.w3schools.com/jsref/event_touchend.asp) events to provide better mobile support.
https://user-images.githubusercontent.com/796443/228497653-228c67b9-dd6a-4a0a-9412-c12da48ed614.mov …
=> 🐞 fix(Popover): prevent event bubbling to parent

packages/doc/content/components/components/datepicker/index.mdx, packages/yoga/src/Datepicker/web/Calendar.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/TVM-785)
The following modifications were made:
-   Allow selecting an end date equal the start date
-   Fix UTC Date comparisons. Ex.: When the start date input has the time 23:59, the wrong day is selected.
Allow selecting an end date equal to start date
=> fix(datepicker): Fix/select range same day

packages/doc/content/components/components/accordion/index.mdx, packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/Accordion.test.jsx, packages/yoga/src/Accordion/web/Content.jsx, packages/yoga/src/Accordion/web/Summary.jsx, packages/yoga/src/Accordion/web/index.js, packages/yoga/src/Banner/web/__snapshots__/Banner.test.jsx.snap, packages/yoga/src/BottomSheet/web/__snapshots__/BottomSheet.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Dialog/web/__snapshots__/Dialog.test.jsx.snap, packages/yoga/src/Drawer/web/__snapshots__/Drawer.test.jsx.snap
Currently, the Yoga Accordion component does not allow for customizing the title. To enhance customization options, we are considering adding the `Accordion.Summary` sub-component as an alternative to the title/subtitle improving its customization capabilities. By using `Accordion.Summary`, we would no longer need to use the title/subtitle prop. Usage Example:
```javascript
<Accordion>
<Accordion.Summary>
<Text>Summary</Text>
</Accordion.Summary>
<Accordion.Content>
<Text>Content</Text>
</Accordion.Content>
</Accordion>
```
Issue: https://github.com/gympass/yoga/issues/664
Go to the `/components/accordion#with-summary` doc page.
=> feat(Accordion): Add accordion summary component resolves #664

packages/yoga/src/Dropdown/web/Dropdown.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/CUP-1216)
- I added a new property to have the option of not having a maximum height in Dropdown.
- I thought of some approaches, such as having the possibility of passing the size, but I think that before adding we would need to align which sizes we would adopt. I followed with this option to give this option for the Dropdown to be able to grow according to the amount of elements it will have.
https://github.com/gympass/yoga/assets/98053923/22d9d881-a559-40ef-a7e2-789a1d5e08ee
=> Added isMaxHeight property in the dropdown

packages/icons/src/ui.js
The `yoga-mat` and `zen` icons were not exported, so I added them
| ![Screenshot 2023-10-04 at 10 23 12](https://github.com/gympass/yoga/assets/32910717/05fa5e79-fc78-402a-9e97-7afa72b1040c) | ![image](https://github.com/gympass/yoga/assets/32910717/a1632cdf-a62a-4bb9-811b-929bfb7f48af) |
=> 🚀 feat(icons): add yoga-mat and zen icons export

packages/yoga/src/Avatar/native/Avatar.jsx, packages/yoga/src/Avatar/native/__snapshots__/Avatar.test.jsx.snap, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
In this PR, borders were added to the avatar.
We are adopting `StyleSheet.hairlineWidth` to ensure consistent and visible borders across all devices. This value automatically adjusts to screen density, offering a delicate aesthetic without compromising visibility. It's a more responsive approach than using a fixed `0.5px`.
|![Simulator Screenshot - iPhone 13 - 2023-10-11 at 09 03 19](https://github.com/gympass/yoga/assets/120468000/6c0f848f-46e5-4bc3-84b7-25ce5d1a8642)|![Simulator Screenshot - iPhone 13 - 2023-10-17 at 16 16 59](https://github.com/gympass/yoga/assets/120468000/8d5baeeb-c98b-4528-b37c-64ccf8925f21)|
=> feat: add border in avatar 🚀

scripts/prepublish.js
These changes are intended to fix errors in testing native projects and fix the issue of not finding the Yoga module in web projects.
=> 🐞 fix(prepublish): update module resolution

packages/doc/content/components/components/spinner/index.mdx, packages/yoga/src/Spinner/Spinner.theme.js, packages/yoga/src/Spinner/index.js, packages/yoga/src/Spinner/web/Spinner.jsx, packages/yoga/src/Spinner/web/Spinner.test.jsx, packages/yoga/src/Spinner/web/__snapshots__/Spinner.test.jsx.snap, packages/yoga/src/Spinner/web/index.js, packages/yoga/src/index.js
This is a new component called Spinner, which can be used as a way to indicate that something is in progress or loading (pages, inputs, buttons, etc).
It receives two optional props: size and color, by default these values ​​are "medium" and "primary".
https://github.com/gympass/yoga/assets/141175689/82e7916d-2536-4480-aec7-95bc1fafe23d
=> Feature: Spinner Component

packages/yoga/src/Avatar/native/Avatar.jsx, packages/yoga/src/Avatar/native/__snapshots__/Avatar.test.jsx.snap, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
This Pull Request introduces a significant change in the behavior of the Avatar component's border. Previously, the border was applied externally to the component, leading to visual inconsistencies, especially related to opacity and alignment with the avatar images.
Implementation Details:
Border Change: The border has been repositioned to be inside the Avatar component. This was done to ensure that the border integrates more harmoniously with the avatar image.
Addition of a Mask Layer: To overcome the issue of images not respecting the border's opacity, a creative solution was adopted. I introduced a "mask layer" that works alongside the border. This approach allows the border to …
=> fix: border in avatar  🚀

package.json
These dependencies were missing and that's why it broke in the pipeline
=> fix(package.json): fix CI error on notify.js file

packages/yoga/package.json
When doing the build, index.js and index.native.js were not appearing, this PR solves this
=> 🐞fix(build): build index.ts and index.native.js

packages/yoga/src/NavigationMenu/web/Menu/Menu.tsx
This PR fix an error caused by importing a component not used anymore
=> fix(navigation-menu): remove not used import

packages/yoga/src/Avatar/native/Avatar.jsx, packages/yoga/src/Avatar/native/__snapshots__/Avatar.test.jsx.snap, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
In this PR, the opacity of the avatar border was only changed
|![Simulator Screenshot - iPhone 13 - 2023-11-21 at 15 37 48](https://github.com/gympass/yoga/assets/120468000/188973f9-a67b-440d-a7d2-12d81f06d1d1)|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-09 at 16 08 55](https://github.com/gympass/yoga/assets/120468000/d8dab8e7-3a9b-4e36-92ac-2e02eba15a1e)|
=> fix: border in avatar 🚀

packages/doc/content/components/components/button/default-web.mdx, packages/doc/content/components/components/button/link-web.mdx, packages/doc/content/components/components/button/text-web.mdx, packages/labnative/pages/Button.jsx, packages/yoga/src/Banner/native/__snapshots__/Banner.test.jsx.snap, packages/yoga/src/Banner/web/__snapshots__/Banner.test.jsx.snap, packages/yoga/src/Button/native/Link.jsx, packages/yoga/src/Button/native/Text.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/Link.jsx, packages/yoga/src/Button/web/Text.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap, packages/yoga/src/Snackbar/native/__snapshots__/Snackbar.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-722)
- Change `<Button />`, `<Button.Link />`, `<Button.Text />`
https://github.com/gympass/yoga/assets/46816386/04c2fcb9-b94a-4ce0-9188-9bfa2722077e
https://github.com/gympass/yoga/assets/46816386/3104530e-2ab3-41f8-896a-e2b7bdef4f84
https://github.com/gympass/yoga/assets/46816386/eb0771d0-3056-426a-87e3-92fdc8cffa8a
https://github.com/gympass/yoga/assets/46816386/158f3587-45e1-4ad1-83af-e1b26ee19681
https://github.com/gympass/yoga/assets/46816386/5e3330a5-af61-43d3-891b-71d9c1c08c41
https://github.com/gympass/yoga/assets/46816386/738d84a7-fa7f-4a19-9fab-55cd46430484
=> 🚀 Feat: change button component

packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/Counter.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap, packages/yoga/src/Chips/web/Chips.jsx, packages/yoga/src/Chips/web/Counter.jsx, packages/yoga/src/Chips/web/__snapshots__/Chips.test.jsx.snap
Update colors and border-radius
background-color: primary to secondary
border-radius: circle
| Before Native | After Native |
|<img width="342" alt="Screenshot 2024-01-17 at 17 18 54" src="https://github.com/gympass/yoga/assets/32910717/a0f42dc6-44ab-4e4e-8c25-627abee25468">|<img width="344" alt="Screenshot 2024-01-17 at 17 16 32" src="https://github.com/gympass/yoga/assets/32910717/29ca1d7d-7be9-4c3b-bb95-ec86d1dbbe64">|
| Before Web | After Web |
|<img width="418" alt="Screenshot 2024-01-17 at 17 18 00" src="https://github.com/gympass/yoga/assets/32910717/c5b4f2a0-3ce6-45f3-b3ec-3f79c …
=> 🚀 refactor(chips): change chips colors and border tokens

packages/common/src/merge.ts
The `merge` helper is currently transforming arrays into objects. This hotfix makes it so that the new array always overwrites the original one.
We should probably add unit tests to this function (if we intend to keep it :D)
Called `createTheme` and checked the output (arrays were being transformed into objects). We've found this, when going through everything and checking that components that used array prototype functions were now breaking because of that :)
=> 🐞 fix: don't change the array type when merging

packages/tokens/src/global/colors.ts
Update `neutralNew` value.
| ![image](https://github.com/gympass/yoga/assets/9873486/c1cf70a5-7fc0-417f-8d90-38fab363d335) | ![image](https://github.com/gympass/yoga/assets/9873486/6b412aee-4146-4452-bedc-c7f696138920) |
=> fix: update `neutralNew` value

packages/yoga/src/Feedback/web/StyledFeedback.jsx, packages/yoga/src/Feedback/web/__snapshots__/Feedback.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/RTN-845)
This PR aims to fix the spacing between action buttons in the `Feedback` component. We noticed due to the rebranding that in the mobile version of this component, there should be a gap of 16px `spacings.small`.
| Current Feedback | Current Figma | Figma Rebranding |
| ----- | ----- | ----- |
| <img width="400" src="https://github.com/gympass/yoga/assets/18193620/70d288dc-f826-4b31-9026-910feaf7ef9b" /> | <img width="400" src="https://github.com/gympass/yoga/assets/18193620/cbc18181-95bf-4621-8bf9-c26fb87fb660"/> | <img width="400" alt="image" src="https://github.com/gympass/yoga/assets/18193620/fa436087-3ceb-4311-980d-5ad8c7dd24ba">|
Figma: …
=>  🐞 fix(RTN-845): updates spacing on feedback action buttons

packages/doc/content/components/components/heading/index.mdx, packages/yoga/src/Heading/Heading.theme.js, packages/yoga/src/Heading/web/BackButton.jsx, packages/yoga/src/Heading/web/RightButton.jsx, packages/yoga/src/Heading/web/StyledHeading.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
We are adding the new `Heading` component style.
| Before | After - V2 | After - V3 |
| ![Screenshot 2024-02-19 at 10 21 09](https://github.com/gympass/yoga/assets/32183575/aacbe7ae-df1a-4ea5-bf51-2ca4dca0be5b) | ![Screenshot 2024-02-19 at 10 18 38](https://github.com/gympass/yoga/assets/32183575/669d2c52-b7d0-437b-8860-38402940be48) | ![Screenshot 2024-02-19 at 10 23 43](https://github.com/gympass/yoga/assets/32183575/5f891950-c62d-41e8-ba4b-47f9efeeba97) |
=> 🚀[RTN-858] - feat(Heading): New heading component style

packages/yoga/src/Heading/web/StyledHeading.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
I removed the min-height on the last PR and I'm implementing it again to avoid other teams having any work like implementing some padding or margin to have the older heading size.
| ![Screenshot 2024-02-22 at 10 17 14](https://github.com/gympass/yoga/assets/32183575/7ac31426-b71a-42f9-a2dc-1d01cb515bed) | ![Screenshot 2024-02-22 at 10 12 52](https://github.com/gympass/yoga/assets/32183575/cc8583ac-2c54-46c4-9876-45aaedb6242d) |
=> 🐞[RTN-858] - Fix min-height on Heading component

packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap, packages/yoga/src/Chips/web/Chips.jsx, packages/yoga/src/Chips/web/__snapshots__/Chips.test.jsx.snap, yarn.lock
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-772)
Inconsistencies were found in the chips, the inconsistencies are declared in the comments of this JIRA:
https://gympass.atlassian.net/jira/software/c/projects/EXUX/boards/1006?selectedIssue=EXUX-302
Web:
---------
Native:
=> 🐞 styles: adjust chips styles

packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3156)
Allow usage of colors not included in theme
```tsx
<PlanCard discount="SAVE 40%" variant="royalblue">
<PlanCard.Content
title="Gold"
currency="$"
price="99.90"
period="/mo"
badgeColor="royalblue"
/>
</PlanCard>
```
|     ![gympass github io_yoga_components_card_plancard(Andre)](https://github.com/gympass/yoga/assets/141146776/f788ecb0-f511-4d9f-8b0e-8de81d907ab8)   |    ![localhost_8000_components_card_plancard(Andre)](https://github.com/gympass/yoga/assets/141146776/b67989dd-98f9-49d8-8055-9267e9dcbb94)  |
=> 🚀 [EUEG-3156] - feat(PlanCard): allow usage of colors not included in theme

packages/tokens/src/global/font-weights.ts, packages/yoga/src/Theme/Provider/web/FontLoader.test.jsx, packages/yoga/src/Theme/Provider/web/GlobalStyle.jsx, packages/yoga/src/Theme/Provider/web/GlobalStyle.test.jsx, packages/yoga/src/Theme/theme/v3theme.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-782)
- Add antialiased for Font-Weight issues
Already been reviewed by designer
| <img width="333" alt="image" src="https://github.com/gympass/yoga/assets/46816386/96a24750-182f-44b6-b621-2b0387969bb8"> | <img width="333" alt="image" src="https://github.com/gympass/yoga/assets/46816386/fc7dd1ab-bf58-45d0-b42c-b49f6a1a82fe"> |
=> [DS-782] Add antialiased for Font-Weight issues

packages/yoga/src/ActionRequirement/native/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/native/ActionRequirement.test.jsx, packages/yoga/src/ActionRequirement/native/__snapshots__/ActionRequirement.test.jsx.snap, packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirement.test.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/RTN-899)
This implementation fixes a warning in `ActionRequirement` title prop where we were sending a `JSX.Element` to show the `Text.Display2` for rebranding. With this we remove a warning because we were sending a different type of prop.
=> refactor: updates title prop to receive text display

packages/yoga/src/Theme/theme/v3theme.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3174)
The `lineAndBorders` must use the `#E1DED7` color instead of `#EFEDE7`.
|   ![localhost_8000_components_avatar (1)](https://github.com/gympass/yoga/assets/141146776/ec727790-3d11-40be-9640-2bc73ca6c688)   |   ![localhost_8000_components_avatar](https://github.com/gympass/yoga/assets/141146776/9576949c-deb6-418a-85ac-49368646deee)    |
|    ![localhost_8000_components_checkbox_default (1)](https://github.com/gympass/yoga/assets/141146776/62486ae1-0800-4e73-a685-bfada3189083)    |   ![localhost_8000_components_checkbox_default](https://github.com/gympass/yoga/assets/141146 …
=> 🚀 [EUEG-3174] - feat(v3theme): use lightNew as lineAndBorders value

packages/yoga/src/Banner/web/__snapshots__/Banner.test.jsx.snap, packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/Button.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap
Adjust button disabled token
|<img width="385" alt="Screenshot 2024-03-01 at 16 04 16" src="https://github.com/gympass/yoga/assets/32910717/2abcb2c1-3e9b-4035-9fd2-ad3a217f1b0a">|<img width="425" alt="Screenshot 2024-03-01 at 16 02 49" src="https://github.com/gympass/yoga/assets/32910717/146dfd70-2739-458b-9a5b-e9b960c95a5a">|
|<img width="590" alt="Screenshot 2024-03-01 at 16 04 51" src="https://github.com/gympass/yoga/assets/32910717/5e84ed17-87c0-494f-98cd-f4a801aadfed">|<img width="595" alt="Screenshot 2024-03-01 at 16 02 19" …
=> 🐞 fix: button disabled color

packages/yoga/src/Theme/theme/theme.js, packages/yoga/src/Theme/theme/v3theme.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-795)
We've added a new property to the theme called `v3theme`. We should be able to use it to create alternate behaviors on components.
For example:
```tsx
const Component = withTheme(({ theme }) => {
const { v3Theme } = theme.yoga;
return  v3Theme ? Button : Button.Outline;
})
```
We've also updated how the custom theme merges with the original one. This now allows us to update the component theme directly:
```ts
// v3theme.ts
export const v3theme = createTheme(tokens => ({
/* ... */
components: {
input: {
width: 400,
},
},
});
```
You can test these changes by editing any component as explained before.
N/A
=> [DS-975] Add theme based customizations support

packages/yoga/src/NavigationMenu/web/BottomItems/BottomItems.tsx, packages/yoga/src/NavigationMenu/web/NavigationMenu.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Actions.tsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-796)
Following https://github.com/gympass/yoga/pull/753 build errors, this PR fixes the associated types, which were wrongly defined.
=> fix: navigation menu types

packages/doc/content/components/components/navigationmenu/props.ts, packages/yoga/src/NavigationMenu/NavigationMenu.theme.ts, packages/yoga/src/NavigationMenu/web/BottomItems/BottomItem.tsx, packages/yoga/src/NavigationMenu/web/BottomItems/BottomItems.tsx, packages/yoga/src/NavigationMenu/web/Item/styles.ts, packages/yoga/src/NavigationMenu/web/Menu/Menu.tsx, packages/yoga/src/NavigationMenu/web/NavigationMenu.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Actions.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Switcher.tsx, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap, packages/yoga/src/yoga.d.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-641)
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-797)
This PR updates `NavigationMenu` so it supports the new v3theme, according to following figma:
https://www.figma.com/file/7ANsLOY4vtuPaRhIxioBqB/%F0%9F%94%92-CONFIDENTIAL---Exploration-CIA?type=design&node-id=228-11643&mode=design&t=seTlQMfKst2O5RR4-0
After analysis with @mateusnroll we saw that we needed a new color `#F6EDDF`, which was added to the theme with the name `sandy`.
The code was also refactored, so that we can keep compatibility with the `default` theme and switch between it and `v3`.
Additionally, so user can set a custom `icon` to `Navigation.Menu`, a …
=> 🚀 feat (DS-797): revamp navigation menu to v3 theme

packages/yoga/src/Checkbox/web/Checkbox.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-805)
PR https://github.com/gympass/yoga/pull/726 introduced a change that removed the "htmlProps" from being passed to checkbox input. This breaks some applications that are relying on attributes such as `id` or `name` to work with the element. This PR fixes that, by reintroducing the passage of `...restWithoutEvents` props.
|![Screenshot 2024-03-12 at 18 31 14](https://github.com/gympass/yoga/assets/796443/707cc391-d85a-40fa-b84d-810d27582cc1)| ![Screenshot 2024-03-12 at 18 26 48](https://github.com/gympass/yoga/assets/796443/5249e587-5e72-49c7-9225-2055658ceb8c)|
=> 🐞 fix (DS-805): spread checkbox attributes props to input

packages/yoga/src/NavigationMenu/web/BottomItems/BottomItems.tsx, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-668)
This PR fixes the position of the menu bottom items, which is hiding some edit buttons in the pages.
|![image](https://github.com/gympass/yoga/assets/32453477/80b71dd5-bad6-474a-beb2-b74d511d8c07)|![image](https://github.com/gympass/yoga/assets/32453477/c634affd-759c-4299-93e0-535c7cea3403)|
=> 🐞fix (PPE-668): menu bottom items

packages/doc/content/components/components/skeleton/skeleton-web.mdx, packages/yoga/src/Skeleton/Skeleton.theme.js, packages/yoga/src/Skeleton/native/Skeleton.jsx, packages/yoga/src/Skeleton/native/Skeleton.test.jsx, packages/yoga/src/Skeleton/native/__snapshots__/Skeleton.test.jsx.snap, packages/yoga/src/Skeleton/web/Skeleton.jsx, packages/yoga/src/Skeleton/web/Skeleton.test.jsx, packages/yoga/src/Skeleton/web/__snapshots__/Skeleton.test.jsx.snap
[![DS-790](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/)
Adjusts the background of the Skeleton component
[DS-790]: https://gympass.atlassian.net/browse/DS-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DS-790] Feat/fix skeleton component

packages/yoga/src/Heading/web/Title.jsx, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
We are updating the Title component to use the correct new Text style component.
| Before | After - rebranding - false  | After - rebranding - true | After - CSS Title |
| ------ | ----- | ----- | ----- |
| ![Screenshot 2024-03-18 at 15 13 06](https://github.com/gympass/yoga/assets/32183575/e8f8e17e-09b7-4d4e-a04a-ae3d4cdfac5d) | ![Screenshot 2024-03-19 at 10 03 45](https://github.com/gympass/yoga/assets/32183575/de7e75c3-36f3-45a9-83df-cff0308da3f4) | <img width="341" alt="Screenshot 2024-03-21 at 11 19 40" src="https://github.com/gympass/yoga/assets/32183575/5e1760e3-e0c2-47c8-83ab-9bd33ef45813"> | <img width="192" alt="Screenshot 2024-03-21 at 11 20 …
=> 🚀 [RTN-924] Update Heading component to use the correct font-weight

packages/yoga/src/BottomSheet/web/__snapshots__/BottomSheet.test.jsx.snap, packages/yoga/src/Card/native/Card/Card.jsx, packages/yoga/src/Card/native/EventCard/EventCard.jsx, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/web/Card/Card.jsx, packages/yoga/src/Card/web/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/web/EventCard/EventCard.jsx, packages/yoga/src/Card/web/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Dialog/web/__snapshots__/Dialog.test.jsx.snap, packages/yoga/src/Drawer/web/__snapshots__/Drawer.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-784)
Adjust the `EventCard` component to be aligned with the rebranding design by doing the following updates:
- Change ButtonLink color 
- Remove the shadow
- Add border
**Event Card**
| Before (Native)  | After (Native)  |
|    <img width="290" alt="image" src="https://github.com/gympass/yoga/assets/60697831/87a0a0ff-0754-4ece-bb62-cc469439c5ab"> |      <img width="290" alt="image" src="https://github.com/gympass/yoga/assets/60697831/3ba238f5-d926-4760-a4fc-a809e6b5e24f"> |
| Before (Web)  | After (Web)  |
|    ![image](https://github.com/gympass/yoga/assets/60697831/2f59f45e-d95d-4dcf-9448-0cb9397bcb83) | …
=> 🚀 [DS-784] Update EventCard component

packages/yoga/src/ActionRequirement/native/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/native/ActionRequirementStyles.js, packages/yoga/src/ActionRequirement/native/__snapshots__/ActionRequirement.test.jsx.snap, packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirementStyles.js, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
Update ActionRequirement component to use the correct font-weight
| Before - web | After - web | After v3theme - web |
| ![before-changes](https://github.com/gympass/yoga/assets/32183575/40f869d8-8648-4f2f-aa34-6e4e807cc7a1) | ![after-changes](https://github.com/gympass/yoga/assets/32183575/f52f0fe2-2fe1-4c9b-b8a4-105e8b93e1fa) | ![Screenshot 2024-03-20 at 15 40 43](https://github.com/gympass/yoga/assets/32183575/aee8b4f6-3148-497a-8d28-0c87b0be768a) |
| Before - mobile | After - mobile | After v3theme - mobile |
| ----- | ----- | ----- |
| …
=> 🚀 [RTN-938] - Update ActionRequirement component to use the correct font-weight

packages/yoga/src/Datepicker/web/Calendar.jsx, packages/yoga/src/Datepicker/web/Datepicker.test.jsx, packages/yoga/src/Datepicker/web/__snapshots__/Datepicker.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/RTN-933)
Update `Datepicker` component to use the correct font-weight.
| Before - web | After - web | After v3theme - web |
| ![image](https://github.com/gympass/yoga/assets/18193620/ccb00919-a381-4cf3-9d82-b5c44209c106) | ![image](https://github.com/gympass/yoga/assets/18193620/2e2951c3-7680-4fb6-b3b7-78b994adae86) | ![image](https://github.com/gympass/yoga/assets/18193620/aec268ff-47aa-4ffe-bbe9-18da7d6d3045) |
=> 🚀 [RTN-933] Update Datepicker component to use the correct font-weight

packages/yoga/src/Feedback/web/Feedback.jsx, packages/yoga/src/Feedback/web/StyledFeedback.jsx, packages/yoga/src/Feedback/web/__snapshots__/Feedback.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/RTN-925)
We are updating the `Text` and `Title` components inside `Feedback` component to have correct font-weight
| Before | After - rebranding - false | After - rebranding - true |
| <img width="362" alt="before-change" src="https://github.com/gympass/yoga/assets/32183575/477b5370-469e-4087-889a-5252dc1e263d"> | <img width="361" alt="after-rebranding-false" src="https://github.com/gympass/yoga/assets/32183575/46301217-dd23-4b46-b7d2-aa84d1aada08"> | <img width="357" alt="after-rebranding-true" src="https://github.com/gympass/yoga/assets/32183575/cb09b3fe-4ee7-40ee-a075-44d036642538"> |
=> 🚀 [RTN-925] - Update Feedback component to use the correct font-weight

packages/labnative/core/CenteredView.jsx, packages/yoga/src/Slider/native/Tooltip.jsx, packages/yoga/src/Slider/native/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Slider/web/Tooltip.jsx, packages/yoga/src/Slider/web/__snapshots__/Slider.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-814)
Updated the Text components inside the Slider component.
I've also taken the opportunity to add a `v3theme` toggle on the labnative workspace.
On the web, add the `v3theme` to the Provider, and on the native use the new toggle.
| OS      | Current                                                                                       | After                                                                                         | After (`v3theme`)                                                                             |
|---------|-----------------------------------------------------------------------------------------------|------------------------------------------------------ …
=> [DS-814] Change Slider texts

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/Input.theme.js, packages/yoga/src/Input/native/Helper.jsx, packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/native/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/native/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/Fieldset.jsx, packages/yoga/src/Input/web/Helper.jsx, packages/yoga/src/Input/web/Label.jsx, packages/yoga/src/Input/web/Legend.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Phone.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/native/__snapshots__/TextArea.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap, packages/yoga/src/Theme/theme/v3theme.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-813)
- Update `Input` and `TextArea` components to `v3theme`
- Wrap the component with `<ThemeProvider theme={v3theme}> </ThemeProvider>` and check if it follows the figma
`TextArea Web` 
| ![v2InputWeb](https://github.com/gympass/yoga/assets/46816386/e837acd8-c2f4-4156-bfe5-87c1dc9e62cf) | ![v3InputWeb](https://github.com/gympass/yoga/assets/46816386/a3e19993-e6eb-484f-80b2-140ce90d0c22) |
`TextArea iOS` 
| ![textareav2ios](https://github.com/gympass/yoga/assets/46816386/27a1e4f4-671a-4e62-8a23-e40b606d5b9f) | ![textareav3ios](https://github.com/gympass/yoga/assets/46816386/bc82a6c9-6f0b-4645-bdb6-5bd82eef7933 …
=> [DS-813] Add v3Theme to Input component

packages/yoga/src/Snackbar/native/Snackbar.jsx, packages/yoga/src/Snackbar/native/__snapshots__/Snackbar.test.jsx.snap, packages/yoga/src/Snackbar/web/Snackbar.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-812)
Adjust font to v3Theme
https://github.com/gympass/yoga/assets/32910717/c3dfd61f-2e02-4fc2-9910-3715083a0de7
https://github.com/gympass/yoga/assets/32910717/82ebe30d-3890-4076-8b46-947fe99d2c13
https://github.com/gympass/yoga/assets/32910717/71d79e6a-2c37-4577-8bb9-3b0880dbfd46
=> 🚀 refactor(snackbar): update snackbar font v3theme

packages/yoga/src/Dropdown/Dropdown.theme.js, packages/yoga/src/Dropdown/native/Dropdown.jsx, packages/yoga/src/Dropdown/native/Options.android.jsx, packages/yoga/src/Dropdown/native/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Theme/theme/v3theme.ts
Update Dropdown component to add v3theme
Web Dropdown After
https://github.com/gympass/yoga/assets/141175689/6d488623-8281-4093-8ed3-67ebcacb73e1
Web Dropdown Before
https://github.com/gympass/yoga/assets/141175689/0eee49fe-795d-4050-885c-839fe2c43967
Native Dropdown After
https://github.com/gympass/yoga/assets/141175689/8c845cff-6ac8-4990-8fa1-790bff391e13
Native Dropdown Before
https://github.com/gympass/yoga/assets/141175689/f784f718-62d6-4cf9-a8de-af0dfb27962c
=> [DS-809] Add v3theme to Dropdown component

packages/doc/content/components/components/button/outline-native.mdx, packages/doc/content/components/components/button/outline-web.mdx, packages/doc/content/components/components/button/outline.mdx, packages/labnative/pages/Button.jsx, packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/index.native.js, packages/yoga/src/Button/native/Button.test.jsx, packages/yoga/src/Button/native/Outline.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-815)
This PR adds the `Button.Outline` components to the Yoga native.
You could run the `labnative` project and look at the buttons to see the new button.
Ps.: I didn't take an iOS screenshot because the iOS project is not running on my machine.
=> [DS-815] - Add Button.Outlined to the native

packages/yoga/src/Card/native/Card/Card.jsx, packages/yoga/src/Card/native/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/native/GymCard/CheckIn/__snapshots__/CheckIn.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ENG-5779)
- Adjust the native `EventCard` shadow
- Add conditional to set `elevation` that creates shadows on Android
| Before (Native) | After (Native) |
| <img src="https://github.com/gympass/yoga/assets/45827925/77316153-2b19-45c2-9cef-ada4fab30f73" width="350px" /> | <img src="https://github.com/gympass/yoga/assets/45827925/373bc846-88ac-4dc7-8881-275f85f7e64a" width="350px" /> |
=> 🐞 [ENG-5779] - Fix to remove android shadow on EventCard

packages/yoga/src/NavigationMenu/web/Item/styles.ts, packages/yoga/src/NavigationMenu/web/Menu/Menu.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Switcher.tsx, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-823)
Adjust:
H4 to Display4
Text to Text.Body1
Text.Small to Text.Body2
Currently, the doc is breaking when using V3 and has affected the NavigationMenu, it's already like this in the master. So take a look at the text properties. 
PS: the NaN Holo font doesn't work in the doc.
=> 🐞refactor(NavigationMenu): Adjust Text

packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Divider/web/Divider.jsx, packages/yoga/src/Divider/web/__snapshots__/Divider.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-826)
Safari is not recognizing some Divider css which it is not rendering correctly. 
The 
Safari screenshots:
|    <img width="441" alt="Safari" src="https://github.com/gympass/yoga/assets/9531640/e6f1ca4b-0550-47f8-b3ce-063cb1b72e28"> |   <img width="411" alt="Captura de Tela 2024-04-18 às 09 55 17" src="https://github.com/gympass/yoga/assets/9531640/139d2ca4-fb63-418a-9b60-cbcd48c0ce1f"> |
=> [DS-826] - Fix Divider not showing in Safari 🐞

.github/workflows/main.yml, sonar-project.properties
The AppSec team is creating this pull request to add the necessary components for the integration with SonarCloud to all Gympass's active repositories.
=> Implementing SonarCloud integration

packages/yoga/src/NavigationMenu/web/Switcher/Switcher.tsx, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-830)
The build wasn't working, the ´color´ property was overloading the ´<Text.Tiny>´ component
Removing the color prop and adding it to the styled-components solved the issue
=> 🐞 fix(build): adjust Text props used in the Switcher component

.github/workflows/main.yml, package.json, sonar-project.properties
=> ci: sonar config

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap, yarn.lock
The ActionRequired component uses a `<div>` nested within a `<p>` tag in the list prop. This leads to hydration errors in React. In Next.js applications, this can cause a discrepancy between server-rendered and client-rendered styles, resulting in misaligned or incorrect styling on the page.
https://nextjs.org/docs/messages/react-hydration-error
Just use the ActionRequirement in a NextJS project and the error should be gone.
|  <img width="1079" alt="before-update" src="https://github.com/gympass/yoga/assets/20171541/49e6ec54-0eda-47de-936f-5277c94a8348">  |   <img width="1113" alt="after-update" …
=> 🐞  fix: fix <div> nested in a <p> tag causing error on hydratation

packages/illustrations/README.md, scripts/prepublish.js
=> Fix illustrations release

scripts/prepublish.js
Fix log in prepublish commit and add a new log in error catch
=> fix: fix prepublish

packages/icons/src/flags.ts, packages/icons/src/svg/flag_unitedarabemirates.svg
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/TVM-1851)
- Add new country flag icon (United Arab Emirates).
|    Without    |![image](https://github.com/gympass/yoga/assets/59899974/c7746b94-08a4-4e74-8b77-68732fb18797)|
=> 🚀feat(icons): add new country flag

packages/illustrations/src/index.ts, scripts/prepublish.js
=> ci: debug illustrations package

.github/workflows/main.yml
Includes new action to run the build step before the PR is merged
=> ci: include build step

packages/system/src/border/border.test.js, packages/system/src/border/index.ts, packages/system/src/border/types.ts, packages/tokens/src/index.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-846)
- add border types
- Run the project and check the documentation
`not applicable`
=> [DS-846] - Create border types

packages/system/src/overflow/index.ts, packages/system/src/overflow/overflow.test.js, packages/system/src/overflow/overflow.ts, packages/system/src/overflow/types.ts
=> 🚀 feat(system): add types to overflow

packages/system/src/unit.js, packages/system/src/unit.test.ts, packages/system/src/unit.ts
=> 🚀 feat(system): add types to unit file

packages/yoga/src/Result/native/Result/TextWithBadge/index.tsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EXUX-950)
TextWithBedge re-render issue fix
=> fix: [EXUX-950] TextWithBedge re-render issue fix

packages/yoga/src/Result/native/Result/TextWithBadge/index.test.tsx, packages/yoga/src/Result/native/Result/index.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-868)
Add fragment to `Avatar` component on `Result`.
Update `TextWithBadge` test
=> fix: [DS-868] Revert result avatar fragment removal

packages/common/src/merge.ts, packages/yoga/src/Theme/index.ts, packages/yoga/src/Theme/theme/index.js, packages/yoga/src/Theme/theme/index.ts, packages/yoga/src/Theme/theme/theme.ts, packages/yoga/src/index.ts
- Add types to `theme`
- Add types to `merge` function
=> 🚀 feat(yoga): add types to theme

packages/common/src/dummy.ts, packages/common/src/index.ts
- Remove the `dummy.ts` file to update the package
=> 🚀 refactor(common): remove dummy.ts file

CONTRIBUTING.md
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-861)
CONTRIBUTING.md improvements.
`not applicable`
- Check CONTRIBUTING.md file
`not applicable`
=> [DS-861] - Improve Yoga Contributing Guide

packages/yoga/src/Input/native/Helper.jsx
This PR adjusts the native `Input`'s Helper component max-width when the prop `full` is enabled. The character counting element is not being aligned to the far right.
|    <img width="339" alt="image" src="https://github.com/user-attachments/assets/6a139b88-45e0-4ba6-9069-daee0effc06f">  |     <img width="339" alt="image" src="https://github.com/user-attachments/assets/18a246e8-0f3d-4977-b8b9-ad4bb8771de3"> |
=> 🚀 fix(input): helper wrapper max width

packages/doc/content/components/components/feedback/index.mdx, packages/yoga/src/Feedback/web/Feedback.jsx, packages/yoga/src/Feedback/web/Feedback.test.jsx, packages/yoga/src/Feedback/web/StyledFeedback.jsx, packages/yoga/src/Feedback/web/index.js
In this PR, `Feedback.Caption` has been added as a new child of the Feedback component.
To give context, we need to add information on the Cancellation Success screen for primary users. To do this, we need to update the feedback component with an option to add one more description (Caption). 
This will give the user more information about their cancellation. 
To more details: [task history](https://gympass.atlassian.net/browse/RTN-1539) and [figma](https://www.figma.com/design/RofGB6OCJEP7kcguw3TpQy/%5BRetention%5D-Cancel-and-Pause-(Rebranding)?node-id=13550-88709&node-type=instance&t=X3u0dllQjm13501y-0)
| V3Theme  | V2Theme |
| <img …
=> RTN-1557: Update Feedback component to receive Caption as a new child component

packages/yoga/src/Feedback/web/StyledFeedback.jsx, packages/yoga/src/Feedback/web/__snapshots__/Feedback.test.jsx.snap
[![JIRA Issue](https://gympass.atlassian.net/jira/software/c/projects/ACS/boards/1348?assignee=712020%3A4448bab7-b24c-4e4b-bd76-7d9e3e1c3b36&selectedIssue=ACS-57)
I adjusted the heading level so that the screen reader reads the title correctly
=> 🚀 Feat: adjust heading level

packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Checkbox/web/Checkbox.test.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap
adjustment in checkbox accessibility, ios becomes unavailable with focus, with this change ios will work normally
=> 🚀 Feat: check box accessibility

.github/workflows/main.yml, packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Checkbox/web/Checkbox.test.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap, packages/yoga/src/hooks/index.js, packages/yoga/src/hooks/useId.js
The checkbox component used a hook to generate id that was introduced in react 18, causing incompatibility in some other projects. The id was generated manually, without external dependencies.
=> 🐞 Correction in checkbox id generation

CODEOWNERS
=> chore(codeowners file): update CODEOWNERS file

packages/yoga/src/Button/web/Icon.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap
Previously, when the disabled prop was omitted, the attribute `disabled` would resolve to `false` due to `isLoading` default value, but `aria-disabled` would be omitted due to passing `undefined` value to a styled component removes the attribute:
```jsx
const ButtonIcon = forwardRef(
(
{
// ...
disabled, // defaults to undefined
isLoading, // defaults to false
...props
},
ref,
) => {
return (
<IconStyled
{...props}
ref={ref}
small={small}
disabled={disabled || isLoading} // rendered as disabled='false'
aria-disabled={disabled} // ignored
isLoading={isLoading}
>
);
```
It could be fixed, however it is unnecessary. The disable attribute in buttons is enough ([stack overflow](https://stackoverflow.com/questions/38059140/when-to-use-the-disabled-attribute-vs-the-aria-disabled-attribute-for-htm …
=> fix(ButtonIcon): remove unnecessary `aria-disabled` from component

packages/doc/content/components/components/input/phone.mdx, packages/yoga/src/Input/web/Phone.jsx, packages/yoga/src/Input/web/Phone.test.jsx
The phone input does not accept custom events today, this PR aims to fix this issue.
B
https://github.com/user-attachments/assets/f07a943e-1db3-49ed-884c-d22c745d4971
https://github.com/user-attachments/assets/ec21b0ee-443c-4fe1-8b13-871c383d3127
=> 🚀 Fix: propdown props correctly to phone input 

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirement.test.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirementStyles.js, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
Add prop titleLevel to ActionRequirement to apply accessibility especification.
=> [ACS-82]: 🚀 Add prop titleLevel to ActionRequirement 

packages/doc/content/components/components/datepicker/index.mdx, packages/yoga/src/Datepicker/web/Calendar.jsx, packages/yoga/src/Datepicker/web/Datepicker.jsx, packages/yoga/src/Datepicker/web/Datepicker.test.jsx
- Includes the locale prop that is used to translate the dates of the Datepicker and Calendar components. Locale must be a valid date (navigator.language type). Using the locale as a prop maintains flexibility in the component, with the default being 'en-US'.
- Translation of the months, days of the week and the selected date displayed in the Selector.
- Maintains the 'en-US' standard, starting the dates with capital letters and displaying the month abbreviation in 3 letters in the Selector, maintaining the format 'mmm d, yyyy'.
|![Screenshot 2025-03-14 at 10 56 19](https://github.com/user-attachments/assets/fc185da9-8040-4c39-b099-355d9dd22a9f)|![S …
=> DS-1037 - Adjust datepicker language

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Input.test.jsx
The aria label was added to the clear button, it wasn't working
=> 🚀ACS-129 - Accessibility clear button

packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/Accordion.test.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
The Accordion is currently using `Text.Medium`, but we should use `Text.Body1` instead of the deprecated `Text.Medium`, ensuring alignment with rebranding standards.
| V2 | V3 |
|![Screenshot 2025-03-18 at 17 53 01](https://github.com/user-attachments/assets/59574a36-61a0-4cb6-9845-6cbc073ad2aa)|![Screenshot 2025-03-18 at 17 54 38](https://github.com/user-attachments/assets/2ea8f7f6-8dde-4a86-a4b4-8cee8a70cbf3)|
| V2 | V3 |
|![Screenshot 2025-03-18 at 17 47 17](https://github.com/user-attachments/assets/2696f87a-3d87-493b-8209-4623d84a6fbb)|![Screenshot 2025-03-18 at 17 57 …
=> [RTN-1754] Update Accordion component

packages/yoga/src/Button/native/Button.jsx, packages/yoga/src/Card/native/EventCard/EventCard.jsx, packages/yoga/src/TextArea/native/TextArea.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/CODEME-1687)
After the changes on https://github.com/gympass/yoga/pull/881 we noticed some issues with handling props for two native components: `<TextArea />` and `<EventCard />`. This PR intend to fix the issues that was affecting client apps.
Not applicable
=> 🐞 fixes prop handling regressions on native components

packages/icons/src/ui.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PAC-1166)
Fix SingleWomanFlag icon name
=> fix: adjust SingleWomanFlag icon name

.github/workflows/main.yml
Fix sonar error about deprecated action by updating to v5.2.0.
=> ci: fix sonar action
