gympass/yoga

packages/doc/content/components/components/themeprovider/index.mdx, packages/yoga/src/Theme/Provider/ThemeProvider.jsx
This PR adds the documentation for `ThemeProvider` component.
The component documentation contains:
- Reference (what this component does)
- Usage (when and how to use it)
- Props (properties you can pass to change it behavior)
=> [DS-87] ThemeProvider Documentation

packages/yoga/src/Dropdown/native/Dropdown.jsx, packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Input/native/Input.jsx, packages/yoga/src/Input/web/Input.jsx
In this PR, I'm changing the propTypes for the Input and Dropdown components, so they are able to accept numbers without throwing warnings.
* Create a Input component like so 
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Input, ThemeProvider } from '@gympass/yoga';
const App = () => 
<ThemeProvider>
<Input
label="Find an activity"
helper="Helper text"
maxLength={20}
value={1}
onChange={e => setValue(e.target.value)}
onClean={cleaned => setValue(cleaned)}
/>
</ThemeProvider>
ReactDOM.render(
<App />,
document.getElementById('root')
);
``` 
* Check the browser's console. There should be the following warning:
```Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `ForwardRef`, expected `string`.```
* [Example](https://5w6dr.csb.app/) …
=> Change Input and Dropdown value proptypes so they accept numbers

packages/yoga/src/List/web/LinkItem.jsx, packages/yoga/src/List/web/ListItem.jsx, packages/yoga/src/List/web/__snapshots__/List.test.jsx.snap
We should add `box-sizing: border-box;`to the list elements.
Before:
After:
=> Add 'box-sizing border-box' to List.LinkItems

packages/tokens/src/global/colors.js, packages/yoga/src/Theme/themes/Gyms.js
The colors of the partner theme are out of date in relation to what our PDs have been using in the prototypes.
According to them our theme must be composed by New York as primary our primary color scheme and São Paulo as secondary.
✅ Also updated New York color scheme according to the new pallet :wink:
=> [Partners] Theme colors update

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/TextArea.jsx, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap, packages/yoga/src/Theme/helpers/themeReader/native/native.test.jsx, packages/yoga/src/Theme/helpers/themeReader/web/web.test.jsx
This PR solve two related bugs:
- Fixes #138 
- Fix input helper text when the parent element has a bigger width than Input.
**Bug** example:
**Fixed** example (bordered parent with bigger width):
=> Fix Input and TextArea width issues

packages/icons/README.md, packages/icons/babel.config.js
This PR removes svgo from our web (cjs and esm) build steps. The issue with that was shown in our CI, [here](https://github.com/Gympass/yoga/runs/796226626?check_suite_focus=true#step:8:34).
Since we add only optimized `svgs` inside icons package, we do not need to svgo config inside babel too.
=> Fix svg issues on our build process

packages/icons/babel.config.js, packages/icons/package.json, packages/yoga/package.json, yarn.lock
This PR adds @dr.pogodin/babel-preset-svgr to handle SVG files during the build process of yoga-icons package.
=> Add SVGR to yoga-icons build steps

packages/doc/content/components/components/text/default-native.mdx, packages/doc/content/components/getting-started/default-native.mdx, packages/doc/content/components/getting-started/default-web.mdx, packages/doc/content/components/getting-started/index.mdx
Hi guys, how are you? :rocket:
It is a pleasure to contribute to this incredible project. I found an item about the documentation where I went through difficulty.
The native font import documentation was in the `Text` component. The components are listed in alphabetical order, so the `Text` component becomes one of the last items, making it difficult to access font import documentation.
=> docs(native-font): add documentation for native font in getting started

packages/yoga/src/Input/web/Helper.jsx, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap
The Input error text was being rendered by the `Info` component that was overriding the error text color from `Wrapper`, so I added the error condition on `Info` too to avoid the conflict
Fix #193
=> Fix Input helper text color when affected by an error

packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/CodeBlock/SnackEmbed/SnackEmbed.jsx, packages/doc/src/components/CodeBlock/shared/functions.js, packages/doc/src/components/CodeBlock/shared/index.js, packages/doc/src/components/CodeBlock/shared/templates/native.js, packages/doc/src/components/CodeBlock/shared/templates/web.js, packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Input/web/Fieldset.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
This PR fixes a problem with the codesandbox examples when it has a stateful example.
Ex:
Yoga doc was like this:
```jsx
render(() => {
const [value, setValue] = useState('');
return (
<AutoComplete
value={value}
onChange={value => setValue(value)}
onSelect={selected => setValue(selected)}
onClean={cleaned => setValue(cleaned)}
options={[
'Madrid',
'Milan',
'São Paulo',
'New York',
'Paris',
'Buenos Aires',
'Amsterdam',
'Los Angeles',
'Hollywood',
]}
/>
);
});
```
The codesandbox code was like this (Syntax Error):
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { AutoComplete, ThemeProvider } from '@gympass/yoga';
const App = () => <ThemeProvider >
render(() => {
const [value, setValue] = useState('');
return (
<AutoComplete
value={value}
onChange={value => …
```
=> Fix "codesandbox" code generation

lerna.json, packages/doc/content/components/components/text/default-native.mdx, packages/doc/content/components/components/text/default-web.mdx, packages/doc/content/components/components/text/index.mdx, packages/labnative/pages/Text.jsx, packages/yoga/src/Card/native/GymCard/CheckIn/__snapshots__/CheckIn.test.jsx.snap, packages/yoga/src/Card/web/EventCard/EventCard.jsx, packages/yoga/src/Dropdown/native/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Slider/web/__snapshots__/Slider.test.jsx.snap, packages/yoga/src/Stepper/web/__snapshots__/Stepper.test.jsx.snap, packages/yoga/src/Text/native/Text.jsx, packages/yoga/src/Text/native/Text.test.jsx, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap, packages/yoga/src/Text/textStyle.android.jsx, packages/yoga/src/Text/textStyle.jsx, packages/yoga/src/Text/web/Text.jsx, packages/yoga/src/Text/web/Text.test.jsx, packages/yoga/src/Text/web/__snapshots__/Text.test.jsx.snap
This PR:
- Fix missing prop table on Text component
- Add `size` prop to Text component, setting the font-size rule accordingly to our theme. It must have a value of one of  `xxsmall`, `xsmall`, `small`, `medium`, `large`, `xlarge`, `xxlarge`, `xxxlarge`, or `huge`.
- Add `light` prop to Text component, setting its weight to regular.
=> size and light for Text

packages/doc/content/components/components/text/index.mdx
=> docs: update text patterns to medium size

packages/yoga/src/Icon/Icon.jsx
This fixes a strange behaviour happening in SVG where it disappears and awkward stuff happens when one of its dimensions is undefined by passing them conditionally.
=> Fix width and height usage in Icon component

CONTRIBUTING.md, README.md
**What this does**
- Fix some typos in both `README.md` and `CONTRIBUTING.md`
- Add *contributing* section to `README` (see #206);
- Add as a proposal, the [citizen code of conduct];(https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md), already widely used to this new section;
- Fix `README` "anchoring" to contributors section.
=> Fix README/CONTRIBUTING, add Contributing section to README

.github/workflows/npmpublish.yml, scripts/publish
We already using a GITHUB_TOKEN with required permissions to config actions, but, for some reason, after updating to action/checkout@v2 lerna was facing some permissions issues (not able to push to master branch).
So, looking to a lerna issue in it's repository I've found [this solution](https://github.com/lerna/lerna/issues/1957#issuecomment-702396095).
Also, changed the lerna command that are always forcing a new major version.
=> Stop persisting default github config and fix lerna command

packages/yoga/src/Checkbox/native/Switch.jsx
**Description**
- This explicitly converts `checked` to a Number inside mobile version of `Checkbox.Switch`, to prevent these usages inside our application:
```jsx
// screens/Amenities/Item.js
<Checkbox.Switch
testID="checkBox"
id={item.id}
checked={Number(checked)}
onChange={onChange}
/>
```
=> fix(checkbox-switch): explicitly convert checked to number

packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/CodeBlock/ReactLive/CodeSandboxButton.jsx, packages/doc/src/components/CodeBlock/ReactLive/sandboxConfig.js, packages/doc/src/components/CodeBlock/SnackEmbed/SnackEmbed.jsx, packages/doc/src/components/CodeBlock/shared/templates/native.js, packages/doc/src/components/CodeBlock/shared/templates/web.js, packages/doc/src/components/Documentation/Documentation.jsx, packages/doc/src/components/Layout/Layout.jsx
Our _codesandbox_ and _expo_ examples are showing a strange and wrong `theme` value inside the example code.
Since our major deploy from 6.0.0 version it's not necessary to pass the `theme` prop on `<ThemeProvider />` from our examples. This PR is removing it.
Example from expo snacks:
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/13424727/114223322-0d9bb200-9946-11eb-9a8d-76b4fc03dfe4.png)|![image](https://user-images.githubusercontent.com/13424727/114223455-3cb22380-9946-11eb-8375-c294c21d7432.png)|
=> Fix CodeSandbox and Expo snack examples

jest/config/config.js, jest/config/helpers.js, jest/config/native.js, jest/config/web.js
This PR changes the jest configuration files to bring back the coverage report.
|Before|After|
|------|------|
|![image](https://user-images.githubusercontent.com/13424727/116463884-a33da980-a841-11eb-91f5-9cf9dd2d749b.png)|![image](https://user-images.githubusercontent.com/13424727/116463937-b2245c00-a841-11eb-8fb0-06e9b6b6c124.png)| 
As we can see on the print-screen, we have `93.49%` of code coverage
=> Update jest configuration to fix coverage table

packages/doc/content/components/components/autocomplete/index.mdx, packages/yoga/src/AutoComplete/web/AutoComplete.jsx, packages/yoga/src/AutoComplete/web/AutoComplete.test.jsx
This PR fixes the issue that "onSelect" event was being called when the user clicks on the "Clear (X)" button.
|Before|After|
|------|-----|
|![autocomplete-before](https://user-images.githubusercontent.com/13424727/117195283-7fd3ab00-adbb-11eb-9abb-b90a176062e0.gif)|![autocomplete-after](https://user-images.githubusercontent.com/13424727/117195325-88c47c80-adbb-11eb-8473-d47759ad7f32.gif)|
=> Fix AutoComplete onClean/onSelect event

packages/doc/content/components/helpers/media.mdx
The documentation does not have the letter 's' at the end, so importing the library(`@gympass/yoga-helper`) will not work.
That way, you must add the 's' at the end of the import for the library(`@gympass/yoga-helpers`) to work.
=> Add 's' at the end of import yoga-helpers

packages/doc/content/components/helpers/media.mdx
The 'media.min' is present in the documentation, but it is redundant since the topic above has the same function. In addition, using this media in the code will give error for not recognizing the 'min'.
The correct way to use it would be, per example:
```
${media.md``}
```
or
```
${media.not['md']``}
```
=> Remove topic 'media.min' at media

packages/doc/src/components/CodeBlock/ReactLive/sandboxConfig.js
It was observed that when a code is generated in CodeSandBox, where there is a `<></> (fragment)` it will give a certain error. Here is the error example:
One of the solutions would be to put in each component that uses it `<React.Fragment> or <div>`. As in the example below:
However, it can be solved by adding the dependency 'react-scripts', and that way the `<></> (fragment)` will be recognized in all code generated in CodeSandBox from the Yoga documentation. Example:
=> Add 'react-scripts' as dependency

packages/doc/src/components/CodeBlock/CodeBlock.jsx
As the code is, the codesandbox generation is not able to capture the elements that are styled-component styled.
The problem was encountered on the [media page](https://gympass.github.io/yoga/components/helpers/media#usage) when logging in when trying to create the codesandbox from the first usage example.
In short, it was only necessary to add one more conditional when extracting the components, creating a new regex rule. I hope it will be useful for all the documentation, as it will open up a range of possibilities for customizing components. :)
=> Doc: fix import of styled elements

packages/icons/package.json, packages/yoga/package.json
I checked our documentation and we are using the version `^16.9.0`, which's where the `>=16` comes from.
=> Add `react` as a peer dependency to `@gympass/yoga`

packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap
We were using the `<Checkbox />` component, and notice that when we add a large label text the checkbox width is small than defined
- Add `flex-shrink: 0` to `CheckMark` element. The idea is to keep the same width on Checkbox input
- Update tests snapshots
**Before**
**After**
Closes #279
=> fix: fix checkbox width when adding large label text

packages/yoga/src/Card/Card.theme.js, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Card/native/PlanCard/List.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
the planCard does not have a dynamic height and currently when used more than 3 ListItems the
listItems overlap the contents below them, so it was necessary to remove the fixed height aiming to
solve this bug.
for more details you can look at issue #281
=> Removing the fixed height on PlanCard List

packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap
Change the values used in `border-color` and `font-weight` when the `Chips` component is selected. 
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/128411436-50183ebf-f552-4264-aff7-a458ed48ad9b.png" />    |     <img width="300px" src="https://user-images.githubusercontent.com/7108030/128411401-652546f9-3ac3-4d85-9b91-e8f5b8133feb.png" />  |
=> feat(chips): change native style to match the web

packages/doc/content/system/system/overflow.mdx, packages/system/src/index.js, packages/system/src/overflow.js, packages/system/src/overflow.test.js, packages/system/src/system.js
Keeping the work in `@gympass/system`, we're adding the follow new module:
- `overflows` (having all bellow)
- `overflow` `of`
- `overflowX` `ox`
- `overflowY` `oy`
Those updates will be reflected into our Box component as it makes use of the `system` module
=> Add overflow prop to system

packages/doc/src/components/CodeBlock/CodeBlock.jsx, packages/doc/src/components/CodeBlock/shared/modules/modules.js
Adding Result and Avatar Components to yogaNativeComponents modules and changing the findComponent regex so that the imports of the components work correctly and it is possible to view the component in the expo emulator
=> Add Result to YogaNativeComponents modules

packages/labnative/pages/Box.jsx, packages/system/src/fontWeight.android.js, packages/system/src/fontWeight.js, packages/system/src/typography.js, packages/system/src/typography.test.js
Changing the `font-weight` in Android using react native is [a known hacky](https://github.com/facebook/react-native/issues/26193). 
It is not just changing it to `300`, `400`, `700`, or even to `bold`, `normal`, etc. 
You need to change the `font-family` to reflect what you want.
So, who needs to know about it? 
Our system knows now.
<table>
<thead>
<tr>
<th>RN Code</th>
<th>Android</th>
</tr>
</thead>
<tbody>
<tr>
<td>
```jsx
<Box
b="small"
p="small"
borderRadius="small"
borderColor="feedback.success.dark"
display="flex"
flexDirection="column"
alignItems="center"
elevation="small"
bgColor="white"
>
<Box as={Text} fw="bold">
Making
</Box>
<Text>wellbeing</Text>
<Text>universal</Text>
</Box>
```
</td>
<td>
</td>
</tr>
</tbody>
</table>
PS: sorry for not having the system on Text component …
=> Revisiting `fontWeight` on Android

packages/yoga/src/Avatar/web/Avatar.jsx, packages/yoga/src/Avatar/web/__snapshots__/Avatar.test.jsx.snap
The added style already exists in Gatsby CSS Reset from the documentation. In a normal use of the library outside of the yoga project, the stylization ceases to exist.
- **Without the max-width the image goes from the avatar's safe area:**
-  **CSS Reset inside Yoga project:**
- **After modification:**
=> fix(Avatar): add required Avatar styling in web version

packages/yoga/src/Result/native/Attendances.jsx, packages/yoga/src/Result/native/__snapshots__/Result.test.jsx.snap
Add `deep` variation to attendances font color in `Result` component.
|    <img width="300px" src="https://user-images.githubusercontent.com/7108030/133435087-163cf9e5-cb84-4678-a1c1-d957a0fb17b9.png" />    |    <img width="300px" src="https://user-images.githubusercontent.com/7108030/133435102-56147c0e-8c0a-4b85-a5ed-0c5e30bdf692.png" />   |
=> Change attendances font color

packages/yoga/src/Button/web/StyledButton.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Card/web/Card/__snapshots__/Card.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
**Description:**
It was necessary to add text-align: center to keep the button content centered and not break the layout. This setting corrects when the `Button` component receives an `as="a"`, `forwardAs="a"` and also in its natural state.
**Before:**
**After:**
=>  feat(Button): Adjust button content alignment

packages/doc/content/system/system/typography.mdx, packages/system/src/typography.js, packages/system/src/typography.test.js
Keeping the work in `@gympass/system`, we're adding the text align property to typography's module:
- `textAlign`, `ta`
Those updates will be reflected into components that are currently using the `yoga-system` module.
=> Add text align css property into typography module (Yoga system)

packages/system/src/typography.test.js
I believe the title is pretty self-explanatory 😅 
Fixes this:
=> Fix `padding-line-between-statements` rule usage inside `typography`'s spec

packages/doc/content/components/theming/themeGenerator.mdx
I made a proper demo showing our theme generator in action as part of documentation, as well as some minor additions to doc's message.
| Theme | Screenshot |
| --- | --- |
| Default | ![image](https://user-images.githubusercontent.com/28108272/135345089-9e5e06f4-d3b2-4129-ba8e-d47712350fe4.png) |
| Custom | ![image](https://user-images.githubusercontent.com/28108272/135345140-21e79e5f-9d07-4ebb-b5af-87f0aba2629d.png) |
=> [Theme Generator] Add CodeSandbox project to documentation

packages/doc/src/components/Navigation/Navigation.jsx
> "That's one small step for man, one giant leap for mankind."
This PR enables keyboard navigation through our sidebar. ✨ This brings us:
- Improved semantics;
- More accessibility (still room to improve in our documentation in general);
- Room and example for future improvements regarding a11y;
- Fix for #343;
It also apply some considerable refactoring into our Navigation component inside docs
This is the current status of the navigation using macOS' VoiceOver (turn sound on)
https://user-images.githubusercontent.com/28108272/136059501-ce994485-a55a-462d-8eed-7c328d9fb040.mp4
Some decisions made:
- Replace px font-size with rem, since rem adapts based on user's font size configuration;
- Add a little transition and rotation to the Collapsible arrow, illustrating its current state
- Use …
=> [DOCS: A11y | Navigation] Make it accessible through keyboard

packages/doc/src/components/Navigation/Navigation.jsx
I mistakenly forgot to apply indentation (level prop) to this new `<Collapsible />` button. Already fixed, just a visual issue!
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/28108272/136252933-167b8ca9-8101-40fd-88ed-d26a68456db2.png) | ![image](https://user-images.githubusercontent.com/28108272/136253073-46e1b5ef-8d37-489a-9643-795b6d5e6059.png)[^1] |
[^1]: Look at 'Tag' component text indent.
=> [Fix | Doc] Apply indentation to collapsibles

packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Tag/Tag.theme.js, packages/yoga/src/Tag/native/Informative.jsx, packages/yoga/src/Tag/native/__snapshots__/Tag.test.jsx.snap, packages/yoga/src/Tag/web/Informative.jsx, packages/yoga/src/Tag/web/__snapshots__/Tag.test.jsx.snap
Changed the icon usage at the Tag component, start using the Yoga Icon component instead of rendering the icon as an SVG.
As you can see in the below doc screenshot the icon `marginRight` is set as `xxxsmall` and the SVG style has the `margin-right` as `4px`.
=> Start to use Icon Component inside the Tag instead of SVG

packages/yoga/src/Avatar/native/Avatar.jsx, packages/yoga/src/Avatar/web/Avatar.jsx, packages/yoga/src/Avatar/web/__snapshots__/Avatar.test.jsx.snap
This PR fixes an issue found when using the avatar passing the FastImage component as children (`react-native-fast-image`).
for more details you can look at issue #379
=> Fix avatar image flickering on android

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
This intend to remove the "magical" `1000px` width for the legend tag that prevents the input border from overlapping the input label layout (example below)
The update keeps the current behavior of it. We should look forward the future to replace this workaround (kinda gambiarra) with some proper way of preventing it.
https://user-images.githubusercontent.com/28108272/140560003-a274b3bf-e605-4b49-afa2-a0cd8a8e698c.mp4
=> refactor(input-web-legend): replace hacky numbers

.github/workflows/labeler.yml, .github/workflows/npmpublish.yml
This updates workflows to use a token provided by GitHub Actions instead of relying on a pre-configured one.
=> ci: Use actions-provided GitHub token

.github/workflows/npmpublish.yml
After we started using a Github Actions provided token instead of a personal one, we needed to also update the format we're using to authenticate with NPM, which this PR fixes in `npmpublish`'s workflow.
=> fix(npm-publish): use correct format for GH access token

.github/workflows/npmpublish.yml
Continues #389 
We needed to create a new token with a greater push permission in order to making the CI able to work by itself
=> fix(npm-publish): use custom token with greater permissions

packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap
During the rebase I did in @frgiovanna's PR I accidentally updated the height of the dropdown without removing the padding, which misaligned our Chevron. This PRs removes the padding in order to rely on flex to center the element, making it aligned again. 😅 
**Current:**
**Now:**
https://user-images.githubusercontent.com/28108272/141460953-4211704f-0ff3-4564-b0fd-2279b83de5a1.mp4
=> Dropdown: Adjust misaligned Chevron

.github/workflows/main.yml, .github/workflows/npmpublish.yml
- Use the correct lint command in `linter_and_tests` job
- Remove redundant steps from `npmpublish` (every PR will already have them, so we don't need to repeat it) job in order to make it faster
=> Update main job and remove bloat from `npmpublish` workflow

packages/yoga/src/Dialog/web/Dialog.jsx
We were importing content from the icons package relative while it's actually another package.
Thanks for reporting @frgiovanna
=> fix(dialog): replace relative import with package import

packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap
Was noticed that our current Dropdown wasn't working properly with the full prop. 
The problem was happening because, on the previous PR about the component, we weren't passing the `full` prop to Input component. 
In this PR we are solving this
**Before:**
**After:**
=> fix(dropdown): pass the full prop to input component

packages/doc/content/components/components/index.mdx, packages/doc/content/components/helpers/index.mdx, packages/doc/content/components/icons/index.mdx, packages/doc/content/components/theming/index.mdx, packages/doc/src/components/Navigation/Navigation.jsx
- Improve order inference (by removing unneeded 'sorting' prop)
- Fix console errors due to svg receiving directly the `isOpen` prop
- Add explicit order to component screen pages
The goal is to have consistency across browsers and also make more sense for one reading our docs:
| New (default) | New (collapsed) |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/28108272/141503236-a208e9f9-2771-46b7-b0ac-f2aafd58b616.png) | ![image](https://user-images.githubusercontent.com/28108272/141503282-ec6cf8f5-8afe-446b-a45a-443e97992677.png) |
=> [Docs] Reorder component pages and improve ordering inference

packages/yoga/src/Dropdown/native/Options.android.jsx
There was a missing require cycle occurring in Android Options (from native dropdown). This import update fixes it.
=> fix(dropdown-native): options require cycle in android

packages/yoga/src/Progress/native/Progress.jsx, packages/yoga/src/Progress/native/__snapshots__/Progress.test.jsx.snap, packages/yoga/src/Progress/web/Progress.jsx
- Update `Progress` component allowing number with slice (`/`) label to be placed next to the bar and update font color that was using `stamina` as default.
- [Yoga Figma](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/Yoga-Design-System-7.1?node-id=4623%3A3850)
- [Feature Figma](https://www.figma.com/file/WI7iB8gTsIrY4WhWybpDwN/%5BHercules%5D-Product-Restrictions?node-id=3%3A2)
| Mobile Before | Mobile After |
|   <img src="https://user-images.githubusercontent.com/18318587/145090274-1b942244-192e-44cd-b866-d319d4a7f6ad.png" width="300">     |    <img src="https://user-images.githubusercontent.com/18318587/145090284-ce1092f1-55ab-47a2-9f97-63f205154d23.png" width="300">     |
| Web Before | Web After |
|   <img …
=> refactor: Allow number with slice as progress label and update native font color

packages/yoga/src/Divider/native/__snapshots__/Divider.test.jsx.snap, packages/yoga/src/Dropdown/Dropdown.theme.js, packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap
Was noticed that the last version of the dropdown component has a weird behavior when we pass an error text to it. 
This PR fixes it. 
**Changes:**
- Fix arrow Icon behavior
- Change label color 
**Screenshots**
Before:
After:
=> fix(dropdown): fix behavior when we have the error prop

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/Fieldset.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Label.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap
In order to follow the last design of the Input and keep the consistency of our fields, this PR changes the **color of the label in the error state** and the **color of the border in the activated state**.
You can check the design specs [here](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/Yoga-Design-System-7.1?node-id=4670%3A4105).
Before: 
After:
=> refactor(input): change color of label and border

packages/yoga/src/Chips/web/Chips.jsx
Hi :wave:
This PR fix a little problem when we use icons from yoga icons and pass it as a param in Chips component.  
The error:
=> fix(chips): add 'function' option in propTypes of icon prop in Chips component

packages/doc/content/components/components/header/index.mdx, packages/yoga/src/Header/Header.theme.js, packages/yoga/src/Header/index.js, packages/yoga/src/Header/web/Header.jsx, packages/yoga/src/Header/web/Header.test.jsx, packages/yoga/src/Header/web/__snapshots__/Header.test.jsx.snap, packages/yoga/src/Header/web/index.js, packages/yoga/src/index.js
Now Yoga will have its own Header component. :tada: 
This PR adds the flexible Header component in the web version for devs to be able to add what's necessary inside the component.
Check [here](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/branch/Sj85zBa955QwYXRCC8DBWe/Yoga-Design-System-7.1?node-id=20243%3A101373) the specs.
> ℹ️ **INFO**
We don't have the final version of some components used on the Header's design yet, such as the language dropdown and the menu component. When finished, we will need to update the Header's documentation to have all the use cases.
**Desktop:**
**Mobile:**
=> Add Header Component

babel.config.js
After both #431 and #432 PRs are merged, the lib started to throw `ModuleNotFound` error when te latest version is used. The problem is that the logo svg used in the Header component is not added to the `dist` package after babel's build.
Many thx to @frgiovanna for helping me during the discover process.
fix #434
=> fix: add inline-react-svg to prevent missing SVGs after build in esm

packages/doc/content/components/components/snackbar/index.mdx, packages/yoga/src/Snackbar/web/Snackbar.jsx, packages/yoga/src/Snackbar/web/Snackbar.test.jsx, packages/yoga/src/Snackbar/web/__snapshots__/Snackbar.test.jsx.snap
We noticed that our current `<Snackbar/>` was missing a behavior. We would like to show the close button even when we've added the `duration` prop to make it close automatically
- add `hideCloseButton` prop to hide the button when the user needs
- add tests
- adjust snapshot
- adjust documentation
[Figma prototype](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/Yoga-Design-System-7.1?node-id=15654%3A44275)
=> 🎨  Adjust snackbar

packages/yoga/src/Progress/web/Progress.jsx, packages/yoga/src/Progress/web/__snapshots__/Progress.test.jsx.snap
This PR change color and spacing on progress bar label and update test snapshot to fit the new file adjusted:
color: primary -> **secondary**
spacing: xxxsmall -> **xxsmall**
| :-: | :-: |
| <img width="547" alt="image" src="https://user-images.githubusercontent.com/61520601/153887476-eb001e7c-475e-48f1-b71a-01215af1c1dc.png"> | <img width="547" alt="image" src="https://user-images.githubusercontent.com/61520601/153888691-c3010800-8158-49aa-a9bb-74e49c153f31.png"> |
=> 🐛 Adjust style of progress bar label

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/web/Fieldset.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
- moving verification of `disabled` state out of hover and focus-within pseudo-class
- add a new verification within hover and focus-within pseudo-class when is not disabled
- Update tests snapshots
https://user-images.githubusercontent.com/37422384/169911971-918f5066-fab4-47e8-8ef4-da759f496275.mov
https://user-images.githubusercontent.com/37422384/169912010-91534959-8111-4e17-bf12-bbbda839fafa.mov
=> 🐛  fix: fieldset disabled state for border-color

packages/yoga/src/Card/native/PlanCard/PlanCard.jsx, packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/PlanCard.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1725)
Changing the plan card width.
=> [EUEG-1725] - Update width plan card 🚀

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
- Add text color and opacity to fix bug on iOS (Safari)
- Update tests snapshots
=> 🐛 fix: add color text and opacity for input web

packages/yoga/src/AutoComplete/web/__snapshots__/AutoComplete.test.jsx.snap, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/web/Field.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap, packages/yoga/src/TextArea/web/__snapshots__/TextArea.test.jsx.snap
After add a prop on Field when is disabled to iOS the text is showing very light, local was working, the text is showing great, but when update yoga lib the text continue showing very light. This happened because the prop was ignored.
Add webkit this prop. 
| ![Simulator Screen Shot - iPhone 12 - 2022-06-28 at 11 54 21](https://user-images.githubusercontent.com/16164937/176211209-43b598ed-ad8a-4cb8-bd92-de984329bdde.png) | ![Simulator Screen Shot - iPhone 12 - 2022-06-28 at 11 51 33](https://user-images.githubusercontent.com/16164937/176211264-ece70c35-fa3d-4b1c-b1b3-c3c757d85b16.png) |
=> :adhesive_bandage: add -webkit- prop on text fill color on input

packages/doc/content/components/components/tag/informative-web.mdx, packages/yoga/src/Tag/web/Informative.jsx, packages/yoga/src/Theme/theme/theme.js
For **Clients Engagement** team we notice that we need a new color to express a neutral status on the invitation to sign up feature. 
To complete that, we used the <Tag.Informative> component, but that color wasn't there.
|Before|After|
|---|---|
|<img src="https://user-images.githubusercontent.com/6570553/178285521-10536e79-cb33-476e-b969-b177ed951d35.png" width="400"/>|<img src="https://user-images.githubusercontent.com/6570553/178285996-10f67b98-4741-42c9-b287-ce98f8510a72.gif" />|
=> ✨ Add "neutral" variant color for Tag.Informative

packages/yoga/src/Banner/web/__snapshots__/Banner.test.jsx.snap, packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/native/Text.jsx, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/Text.jsx, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-1991)
This PR updates the disabled button text color
| Web Before |
| ------ |
|    <img src="https://user-images.githubusercontent.com/44280864/183172233-5a6e4ca0-d9a2-4678-84ba-63e8450fc07b.png">    |   
| Web After |
| ------ |
|  <img src="https://user-images.githubusercontent.com/44280864/183167398-0407696c-e060-4b67-b9e4-b9065c1b0505.png">   |
| Native Before | Native After |
|    <img src="https://user-images.githubusercontent.com/44280864/183179516-a51cb425-cb2d-4e60-86a0-8f642cda7e8d.png" width="300px">    |    <img src="https://user-images.githubusercontent.com/44280864/183180029-73e067b6-cea3-4ef3-a872-55c4ade91310.png" width="300px">   |
=> 🚀 Improve the contrast in the disable button by updating the text color

packages/yoga/src/Dropdown/Dropdown.theme.js, packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap
[![#595 Issue](https://img.shields.io/badge/issue-%23595-blue.svg)](https://github.com/gympass/yoga/issues/595)
Hello guys! 
To solve the problem with the `dropdown` `button` click, it was necessary to assign a `padding bottom` of sixteen pixels to the `button` component, so that the user can execute its functionality when clicking on the bottom part of the `button`
**For more details access the issue [#595](https://github.com/gympass/yoga/issues/595)**
|    ![image](https://user-images.githubusercontent.com/58890915/211159995-1315ff0c-d0e2-4a61-acde-771894c889c2.png)    |   ![image](https://user-images.githubusercontent.com/58890915/211160130-d73c8d7c-ace2-419f-97eb-626a66d8e982.png)    |
=> fix(dropdown): fix dropdown button click

packages/labnative/babel.config.js
The `labnative` package was throwing errors when running `yarn dev:native:android` and `yarn dev:native:ios` because of this named exports: https://github.com/gympass/yoga/blob/c33949c0b93ecc10be19ee73132cc9778a6a595e/packages/icons/src/index.js#L3-L4
This PR, basically, adds a missing babel plugin to handle these exports.
| ![simulator_screenshot_B3C1B8B3-E3B9-49EA-93E6-3696D50E6FE9](https://user-images.githubusercontent.com/25802240/211375668-65e1947b-52ea-4965-88db-0c707986223d.png) | ![simulator_screenshot_2BC673EF-B42D-47F5-BF7D-F26598BD7DA4](https://user-images.githubusercontent.com/25802240/211375544-2dadebc1-3782-49ad-91c1-cd44b4d366ca.png) |
=> 🐞 Fix labnative error on init

packages/yoga/src/Accordion/web/Accordion.test.jsx, packages/yoga/src/Accordion/web/Content.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
We work at Darwin and have a scenario in which we want to use the accordion without existing padding. We can use change the style in Accordion component but we can't do the same in Accordion.Content.
=>   🚀  feat(accordion): added className to enable edit styles

packages/yoga/src/AutoComplete/web/AutoComplete.jsx, packages/yoga/src/Dropdown/web/Dropdown.jsx, packages/yoga/src/Dropdown/web/__snapshots__/Dropdown.test.jsx.snap, packages/yoga/src/Input/web/Helper.jsx, packages/yoga/src/Input/web/Input.jsx, packages/yoga/src/Input/web/Input.test.jsx, packages/yoga/src/Input/web/__snapshots__/Email.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Input.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Number.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Password.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Phone.test.jsx.snap, packages/yoga/src/Input/web/__snapshots__/Tel.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ITK-469)
This PR adds some accessibility improvements to the Input component, focusing mainly in improving the usability with screen readers:
- Adds two new props to the Input component: `a11yId` and `includeAriaAttributes` (more details about these below);
- Adds `aria-labelledby` to the input element, so that screen readers can announce the label of the input. If no `a11yId` is provided, `aria-label` is added instead (`aria-labelledby` is preferable when there is a visible text that labels an element according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label));
- Adds `aria-describedby` to the input element, referencing the helper as it's …
=> 🚀 feat(Input): add a11y attributes to Input

packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/TVM-994)
- Fix the following `Accordion` warning:
```
The component styled.div with the id of "..." has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
```
- The animations on style components `AccordionContent` and `ArrowWrapper` were not being triggered. 
This PR also fixes that.
- After making the necessary changes, the `Accordion` was tested manually - the behaviour stayed the same, with the addition of the animations now being triggered (as mentioned in the 2nd point of the description of this PR).
- Snapshots were updated. …
=> 🐞 Fix `Accordion` warning - styled components called inside render

packages/doc/content/components/components/tag/default-web.mdx, packages/doc/content/components/components/tag/informative-web.mdx, packages/yoga/src/Tag/web/Informative.jsx, packages/yoga/src/Tag/web/Tag.jsx, packages/yoga/src/Tag/web/Tag.test.jsx, packages/yoga/src/Tag/web/__snapshots__/Tag.test.jsx.snap
- It was added a new prop to `<Tag />` component, called `ellipsis`, that will work together `maxWidth` prop to put, if needs, some ellipsis for large texts.
- With this feature the`<Tag />` component start to accept maxWidth prop too;
This issue was looked by vms team, because one of ours features needs Tag component and some texts are too large, so was needed put ellipsis to hide their.
Default Tag:
Informative Tag:
=> feat(tag): 🚀 add new prop ellipsis for large texts on tag

packages/doc/content/components/components/dialog/index.mdx, packages/yoga/src/Dialog/web/Dialog.jsx, packages/yoga/src/Dialog/web/Dialog.test.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-138)
This PR updates `Dialog` to:
- Be a [forwardRef](https://react.dev/reference/react/forwardRef) so the parent can pass a ref object and perform operations on it. One simple use case is to [move focus to the modal](https://medium.com/@islam.sayed8/trap-focus-inside-a-modal-aa5230326c1b).
- Receive a custom id, so we can have multiple dialog content mounted on the same page.
https://user-images.githubusercontent.com/796443/233376343-ffe137b8-75d2-4cc8-aed6-33bfd068239a.mov
=> 🚀 feat(Dialog): add forwardRef and custom id to dialog

packages/yoga/src/BottomSheet/web/BottomSheet.jsx, packages/yoga/src/Drawer/web/Drawer.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-138)
In the sequence of https://github.com/gympass/yoga/pull/651, i'm adding the `forwardRef` behaviour to `Drawer` and `BottomSheet`.
=> 🚀 feat(Drawer|BottomSheet): add forwardRef to Drawer and BottomSheet

packages/yoga/src/Accordion/web/Accordion.jsx, packages/yoga/src/Accordion/web/__snapshots__/Accordion.test.jsx.snap
This adjustment is necessary due to the new yoga document.
The new document was built using docusaurus and the way this style was done, docusaurus couldn't understand because support for css-in-js is still in development, so problems like this can happen.
After this refactoring, returning a css, docusaurus was able to understand and render the style.
In the future we will go through each component of Yoga with the new DOC to investigate possible issues like this.
=> 🚀 style(accordion): refactor disabled styles structure

packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap, packages/yoga/src/Chips/web/Chips.jsx, packages/yoga/src/Chips/web/__snapshots__/Chips.test.jsx.snap
When using the Chips component, I expected the default behavior should do a normal click, but as it does not have the type declaration it was doing unexpected behavior like submitting a form as this component is a simple button, under the hood, it is expected to be `type="button"` even though is possible to override this config.
=> 🚀  fix(Chips): set type in order to prevent unexpected behaviour

packages/yoga/src/Popover/web/Popover.jsx, packages/yoga/src/Popover/web/__snapshots__/Popover.test.jsx.snap, packages/yoga/src/Popover/web/styles.js
This PR introduces some improvements to `Popover` implementation:
- adds zIndex property with default to 1, so popover content isn't overflowed by subsequent elements.
- included overflow: auto on container so user can scroll if content overflows.
- included a11yId so content is better described for accessibility users.
- adds popover toggle behaviour on enter if the user is using the keyboard to navigate and include basic focus style so user knows where he is while doing so.
|Before|After|
|-|-|
|![popover-before](https://github.com/gympass/yoga/assets/796443/5ae88cdc-0d7a-4d37-be5a-142b2df106ca)|![popover-after]( …
=> chore: improve popover accessibility implementation

packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/PlanCard.test.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2847)
- Add prop `onClick` to `PlanCard.ListItem` component and transform the wrapper in a button to make it accessible
- Change proptype of the prop `text`, it should accept components such as `Skeleton`
```jsx
<PlanCard discount="SAVE 40%">
<PlanCard.Tag variant="informative">Active</PlanCard.Tag>
<PlanCard.Content
title="Gold"
currency="$"
price="99.90"
period="/mo"
badgeColor="energy"
>
<PlanCard.List>
<PlanCard.ListItem icon={Checkin} text="2.900 gyms and studios" onClick={() => foo()} />
<PlanCard.ListItem icon={Dumbbell} text="1x/day standard access" onClick={() => foo()} />
<PlanCard.ListItem icon={User} text="4x/month 1-on-1 sessions" onClick={() => foo()} /> …
```
=> 🚀 feat(PlanCard): Make ListItem clickable

packages/yoga/src/Stepper/Stepper.theme.js, packages/yoga/src/Stepper/native/Dots.jsx, packages/yoga/src/Stepper/native/Line.jsx, packages/yoga/src/Stepper/native/Stepper.jsx, packages/yoga/src/Stepper/native/Stepper.test.jsx, packages/yoga/src/Stepper/native/__snapshots__/Stepper.test.jsx.snap, packages/yoga/src/Stepper/web/Dots.jsx, packages/yoga/src/Stepper/web/Line.jsx, packages/yoga/src/Stepper/web/Stepper.jsx, packages/yoga/src/Stepper/web/Stepper.test.jsx, packages/yoga/src/Stepper/web/__snapshots__/Stepper.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/ENJ-1329)
We add a prop for Stepper receive a custom color.
- use a stepper component with color prop.
=> 🚀 feat(stepper):  add custom color for stepper

packages/yoga/src/Stepper/native/Stepper.test.jsx, packages/yoga/src/Stepper/native/__snapshots__/Stepper.test.jsx.snap, scripts/prepublish.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/CODEME-1118)
This PR should solve an issue with Jest + React-Native, where Jest couldn't find the correct modules.
Build Yoga locally, Run the `prepublishOnly` command, and replace the `yoga/` folder with the contents of the generated `yoga/dist/` file (especially replacing the `package.json` with the generated one).
=> 🐞 Update module resolution fields [CODEME-1118] 

packages/doc/content/components/icons/icons-web.mdx, packages/doc/src/components/Navigation/Navigation.jsx
During development, there are some warning and errors being thrown to the console.
This PR has 2 fixed for them.
One in the Icon documentation page, where a key was missing to each list child:
The other one was a deprecation warning (from styled-components) in the implementation of the chevron icon used in sidebar tree to show each if each node is open or closed:
Manually, browsing the web page (http://localhost:8000/components/icons#web)
=> 🚀refactor: remove some warnings during development

packages/yoga/src/Popover/web/Popover.jsx, packages/yoga/src/Popover/web/Popover.test.jsx, packages/yoga/src/Popover/web/__snapshots__/Popover.test.jsx.snap
[![issue JIRA](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/)
To adjust the behavior for mobile, the onTouch event was removed and the onClick event was preserved to keep the popover open without the need to keep pressing the button.
For this, the click event will be considered the default and a listener has been added for clicks outside the button element. The hover event has been kept as optional, if chosen the click event should be overridden for this behavior.
Keyboard event by default was also kept with click event.
**[BEFORE]**
Bug report video:
https://github.com/gympass/yoga/assets/141175689/d6d39bb0-6958-4a16-9a1d-1b5d8cf1871e
**[AFTER]**
Mobile, after fix with click behavior …
=> fix: fix popover behavior to accept click (default) OR hover event

packages/yoga/src/Snackbar/web/Snackbar.jsx, packages/yoga/src/Snackbar/web/__snapshots__/Snackbar.test.jsx.snap
The Snackbar in the web version had a fixed z-index value (of 100). If there is in the document any other fixed or absolute positioned element with a higher z-index, the snackbar is shown below it.
To avoid this, it is possible to calculate the z-index when the element is rendered traversing the document's nodes, checking the z-index of each one and returning the max value. 
Just to keep the old behavior and guarantee a high value for the property, the minimum value will be 100.
Through the browser, creating a div with a high z-index value (200) in the .mdx
Old behaviour:
Div with z-index greater than 100m snackbar is below.
New behaviour:
=> 🚀 fix: snackbar z-index

packages/yoga/src/Checkbox/web/Checkbox.jsx, packages/yoga/src/Checkbox/web/Checkbox.test.jsx, packages/yoga/src/Checkbox/web/__snapshots__/Checkbox.test.jsx.snap
The checkbox's inner input isn't getting the given value, breaking any form that relies on it (which is important when you have multiple checkboxes with the same name. The formData will have an array of the selected values)
Open the elements tab on your dev tools of choice. If a value is given the input should have it!
=> 🐞 fix(checkbox): set the input value

packages/yoga/src/Input/web/Input.jsx
Prepend any element to the Input element, inside the bordered area:
Added 2 props to the Input component:
- prependElement: which accepts a node (like the rightIcon prop) 
- prependElementWidth: the width of the element passed as prependElement
We proposed the name of the prop do use _prepend_ because other frameworks use this nomenclature, but it can be left to  keep consistency with the already existed _rightIcon_ prop; we used _Element_ to indicate that this prop accepts any element.
The prependElementWidth is used to add a text indent to the Field component, so the text will be indented (without this prop, the text would be placed above the prepended element). Also, there is some ways to avoid this prop, like calculate the size of the rendered element using the ResizeObserver or with …
=> feat: prepend element to Input

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/List.test.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/List.test.jsx.snap, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2946)
- Add `truncate` prop to be able to remove the truncate behavior.
- Add `children` props to add an additional content inside the list item.
```tsx
<PlanCard.ListItem
{...props}
truncate={false}
>
<Avatar />
</PlanCard.ListItem>
```
=> feat(yoga): add props to PlanCard.ListItem

packages/doc/content/components/components/card/plancard-web.mdx, packages/yoga/src/Card/web/PlanCard/List.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-2957)
Fix style from `PlanCard.ListItem` when it has the `onClick` prop.
|    <img src="https://github.com/gympass/yoga/assets/141146776/5aa96c9a-b7a2-4b47-876f-b8c67d4a28b7" width="300px" />   |    <img src="https://github.com/gympass/yoga/assets/141146776/8bffb931-001c-40be-b775-bfbaa63406e0" width="300px" />   |
=> fix(yoga): fix style from PlanCard.ListItem when it is clickable

scripts/prepublish.js
Revert changes in _createPackageJson_ function to add the full path from modules exported in package.json for each package within npm.
Without them, webpack from other projects that use Yoga cannot find the modules:
=> chore: add full path to exports in createPackageJson

packages/yoga/src/Button/web/Button.jsx, packages/yoga/src/Button/web/Icon.jsx
Removes the ariaLabel prop for the aria-label attribute, thus leaving the native use of the attribute as an accessible element. The ariaLabel property will be maintained only for the Icon component as part of the accessible identifier for elements such as title and description.
Removes the ariaLabel prop for the aria-label attribute, thus leaving the native use of the attribute as an accessible element. The ariaLabel property will be maintained only for the Icon component as part of the accessible identifier for elements such as title and description.
=> Remove prop ariaLabel

packages/yoga/src/Avatar/native/Avatar.jsx
We used to encounter an error when trying to open the native avatar document because the propsTable component couldn't locate the newly added props in PR #703.
The solution was to include these new props in propTypes and defaultProps so that propsTable could recognize them.
|![Screenshot 2023-11-07 at 10 33 07](https://github.com/gympass/yoga/assets/32910717/adc22417-4714-41d0-85da-7aad3f87d174)|![image](https://github.com/gympass/yoga/assets/32910717/6c00c28e-bd7f-47b0-bbb7-fcc11dbd6c6e)|
=> 🐞 fix(avatar-native): add propTypes and defaultProps to avatar native

packages/doc/content/components/components/navigationmenu/props.ts, packages/yoga/src/NavigationMenu/web/Menu/Menu.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Switcher.tsx
This PR fixes a warning caused by being inserted a `div` (skeleton) inside a `p`.
=> fix(navigation-menu): remove div inside p

packages/yoga/src/Heading/Heading.theme.js, packages/yoga/src/Heading/web/__snapshots__/Heading.test.jsx.snap
Fixing the max and min width and height off buttons inside Heading component.
| ![Screenshot 2024-02-22 at 13 10 19](https://github.com/gympass/yoga/assets/32183575/9114e90a-bbdb-45ff-b622-d49264f6ca4e) | ![Screenshot 2024-02-22 at 13 09 40](https://github.com/gympass/yoga/assets/32183575/9beff91d-acc3-4743-856c-f723bf54c387) |
=> 🐞[RTN-858] - Fix width and height on Buttons inside Heading component

packages/yoga/src/Dialog/web/Dialog.jsx, packages/yoga/src/Dialog/web/__snapshots__/Dialog.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3147)
Update close button from Dialog.
| Current | V2 |    V3 |
|  <img  src="https://github.com/gympass/yoga/assets/141146776/7e931f97-b511-4bbe-822b-4d6c1b08b065" width="375" /> |   <img  src="https://github.com/gympass/yoga/assets/141146776/e21667a4-aa4c-4c1e-aa54-fe5748a2f4db" width="375" />   |   <img  src="https://github.com/gympass/yoga/assets/141146776/8ed78aa5-889e-440f-85a3-011e8f50aba7" width="375" />     |
=> 🚀 [EUEG-3147] - feat(Dialog): update close button style

packages/yoga/src/Button/Button.theme.js, packages/yoga/src/Button/native/__snapshots__/Button.test.jsx.snap, packages/yoga/src/Button/web/__snapshots__/Button.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3163)
Update text color when button is disabled.
| Before | V2 | V3 |
| ------ | ----- | ---- |
|    ![localhost_8000_components_button_default(Andre) (2)](https://github.com/gympass/yoga/assets/141146776/dd8aeee7-2e71-45c4-8c9e-8a0099b702a5)    |    ![localhost_8000_components_button_default(Andre) (1)](https://github.com/gympass/yoga/assets/141146776/5fb222d6-70fa-4dd7-9c84-b3acd4e0e25a)   |  ![localhost_8000_components_button_default(Andre)](https://github.com/gympass/yoga/assets/141146776/e5460553-8018-4c44-8964-267644b3928a)  |
=> 🚀 [EUEG-3163] - feat(Button): change disabled text color

packages/yoga/src/Input/web/Phone.style.js, packages/yoga/src/Input/web/__snapshots__/Phone.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-794)
This PR forces phone input `flag-dropdown` class to inherit the height of the parent element, so we ensure that dropdown content is always vertically aligned to center, in all applications that use it.
https://github.com/gympass/yoga/assets/796443/e5ec1577-1a6d-4daa-9bc4-612ac8429839
=> 🚀 fix(DS-794): phone input vertical center

packages/yoga/src/Checkbox/web/Checkbox.jsx
This implementation fixes an undesired behavior in the Checkbox: the onChange event was being triggered twice in every user's click:
The fix consists of creating a new object copied from rest but without the onChange property and passing it to the HiddenInput component. What was happening is that the rest was being passed to both CheckboxWrapper and HiddenInput, triggering the onChange twice.
I didn't remove the entire {...rest} passed as prop to HiddenInput to because I don't know if the other props are required in this component.
Manually
=> 🐞  fix: multiple onChange being triggered on Checkbox

packages/doc/content/components/components/navigationmenu/props.ts, packages/yoga/src/NavigationMenu/web/BottomItems/BottomItems.tsx, packages/yoga/src/NavigationMenu/web/NavigationMenu.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Actions.tsx, packages/yoga/src/NavigationMenu/web/Switcher/Switcher.tsx, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-641)
This PR updates NavigationMenu, so the `z-index` values are - by default - to the least amount possible, so it doesn't overlap with other components on a page. Then, i make configurable via prop, so it can be customized by each app.
=>  🚀 fix/feat: downsize "zIndex" values on NavigationMenu and allow it to be configurable

packages/yoga/src/Chips/native/Chips.jsx, packages/yoga/src/Chips/native/__snapshots__/Chips.test.jsx.snap, packages/yoga/src/Chips/web/Chips.jsx, packages/yoga/src/Chips/web/__snapshots__/Chips.test.jsx.snap
This PR implements the update of text nomenclatures in chips, in accordance with the guidelines of the new rebranding. The changes were applied as follows:
- For chips in the `selected` or `disabled` state, the text style was changed from `Text.Bold` to `Text.Overline`.
- For chips in the default state, the text style was updated from `Text` to `Text.Caption`.
These changes ensure that the use of chips is aligned with the new visual identity and improves consistency across the user interface.
|![Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 10 50 44](https://github.com/gympass/yoga/assets/120468000/66079202-14 …
=> 🚀 refactor(chips): adjust chips texts 

packages/yoga/src/Card/web/PlanCard/Content.jsx, packages/yoga/src/Card/web/PlanCard/__snapshots__/PlanCard.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3190)
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-800)
We are updating the PlanCard title component to use the correct new Text style component.
The update was just on the title prop for PlanCard component
| v2 | v3 Before | v3 After |
|--------|--------|--------|
| <img src="https://github.com/gympass/yoga/assets/44280864/b5f9123f-b440-42e0-a25e-f5b97ad6c251" width="300px" /> | <img src="https://github.com/gympass/yoga/assets/44280864/683f997e-5e5e-4434-8e82-c5064b7a27d0" width="300px" /> | <img src="https://github.com/gympass/yoga/assets/44280864/d4dd54a8-01a2-4e4f-bc48-63ac0bb032a9" width="300px" /> |
=> 🚀 [EUEG-3190 | DS-800] Update PlanCard component to use the correct font-weight

packages/yoga/src/Banner/native/Banner.jsx, packages/yoga/src/Banner/web/Banner.jsx
Adjust font to v3Theme
https://github.com/gympass/yoga/assets/32910717/064700d5-60ac-4b51-9770-ad0284df9e4f
https://github.com/gympass/yoga/assets/32910717/a1b9d116-0618-4c5d-8043-0b39004a0cd4
| V2 | V3 |
|<img width="930" alt="image" src="https://github.com/gympass/yoga/assets/32910717/d1092829-211c-4e06-841e-4ba826a1a0d0">|<img width="938" alt="image" src="https://github.com/gympass/yoga/assets/32910717/35ca264c-3f5b-4b81-ae9b-ceb788318f52">|
| V2 | V3 |
|<img width="917" alt="image" src="https://github.com/gympass/yoga/assets/32910717/cd421e7e-4b4b-4e6d-90fd-4541a8cc2262">|<img width="929" alt="image" …
=> 🚀 refactor(banner): update banner font v3theme

packages/yoga/src/BottomSheet/web/__snapshots__/BottomSheet.test.jsx.snap, packages/yoga/src/Dialog/web/Content.jsx, packages/yoga/src/Dialog/web/Header.jsx, packages/yoga/src/Dialog/web/__snapshots__/Dialog.test.jsx.snap, packages/yoga/src/Drawer/web/__snapshots__/Drawer.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EUEG-3194)
Update Dialog component to use the correct font-weight
=> [EUEG-3194] Update Dialog component to use the correct font-weight

packages/yoga/src/NavigationMenu/web/Item/styles.ts, packages/yoga/src/NavigationMenu/web/__snapshots__/NavigationMenu.test.tsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PAC-208)
After updates made on `Tag` component for v3 Theme, the `NavigationMenu` component couldn't customize its `Item` tags font color, being unreadable.
| <img width="1125" alt="image" src="https://github.com/gympass/yoga/assets/26771441/2f8fb9ac-5d92-4c1a-8725-af202322c6b0"> | <img width="1127" alt="image" src="https://github.com/gympass/yoga/assets/26771441/93b4d4ea-c66f-4989-8f02-838a653a61fa"> |
=> 🐞 fix(NavigationMenu): changed item tag font color

packages/system/src/elevation/elevation.android.ts, packages/system/src/elevation/elevation.test.js, packages/system/src/elevation/elevation.ts, packages/system/src/elevation/index.ts, packages/system/src/elevation/types.ts
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-836)
- Add Elevation types
- Run the project and check the documentation
`not applicable`
=> [DS-836] - Elevation typing

packages/system/src/font-weight/fontWeight.android.ts, packages/system/src/font-weight/fontWeight.ts, packages/system/src/font-weight/index.ts, packages/system/src/font-weight/types.ts, packages/system/src/typography.js, packages/system/src/typography.test.js
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-838)
- Add font-weight types
- Run the project and check the documentation
`not applicable`
=> [DS-838] - Font-Weight typing

packages/yoga/src/Avatar/native/Avatar.jsx, packages/yoga/src/Result/native/Result/TextWithBadge.jsx, packages/yoga/src/Result/native/Result/TextWithBadge/__snapshots__/index.test.tsx.snap, packages/yoga/src/Result/native/Result/TextWithBadge/index.test.tsx, packages/yoga/src/Result/native/Result/TextWithBadge/index.tsx, packages/yoga/src/Result/native/Result/TextWithBadge/styles.ts, packages/yoga/src/Result/native/Result/__snapshots__/index.test.jsx.snap, packages/yoga/src/Result/native/Result/index.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/EXUX-930)
Add new `TextWithBadge` component to `Result` component.
**Context**.
It was necessary to implement a new style for custom `TextWithBadge` component because, on Android, using the `Text` component with `numberOfLines={1}` did not correctly respect the timing for applying the truncation/ellipsis. Often, depending on the text length and spacing, the ellipsis/truncation was applied prematurely or extrapolates its container size, resulting in unnecessary empty space after the `Badge` or cutting it off.
This difference in behavior between iOS and Android is a peculiarity of how each platform handles text layout. On Android, spaces are considered in the calculation of when to apply …
=> feat: [EXUX-930] Fix ellipsis/truncate problem on android

packages/system/src/newSystem/defaultProps.ts, packages/yoga/src/Box/native/Box.jsx, packages/yoga/src/Card/native/EventCard/__snapshots__/EventCard.test.jsx.snap, packages/yoga/src/Text/native/Text.jsx, packages/yoga/src/Text/native/__snapshots__/Text.test.jsx.snap
active new system in Box and Text
=> 💣 feat: add new system in Box and Text

packages/yoga/src/ActionRequirement/web/ActionRequirement.jsx, packages/yoga/src/ActionRequirement/web/ActionRequirementStyles.js, packages/yoga/src/ActionRequirement/web/__snapshots__/ActionRequirement.test.jsx.snap
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/AC-5254)
- Add `aria-hidden` attr in the illustration;
- Add `as` attr with `h1` value and `aria-label`  in title components;
- Add `aria-label` in description text
- Add tabIndex in all elements from ActionRequirement
https://www.figma.com/design/8SVndQjnDLmApd3NntMIPQ/Accessibility?node-id=3314-55285&node-type=instance&t=fnXh0R28TsoWG9PT-0
=> feat(ActionRequirement): improve accessibility

packages/yoga/src/Snackbar/web/Snackbar.jsx, packages/yoga/src/Snackbar/web/Snackbar.test.jsx, packages/yoga/src/Snackbar/web/__snapshots__/Snackbar.test.jsx.snap
- Added accessibility to snackbar
- Add custom aria label to close button
=> [ACS] - Add accessibility to snackbar

packages/doc/content/components/components/input/phone-web.mdx, packages/doc/content/components/components/input/phone.mdx, packages/yoga/src/Input/web/Phone.jsx, packages/yoga/src/Input/web/Phone.test.jsx, packages/yoga/src/Menu/web/__snapshots__/Menu.test.jsx.snap
The goal of this PR is to add the prop countries so the child component of input phone can filter the countries options to show in the input phone field.
=> Feat: add countries props for input phone component

packages/yoga/package.json
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/CODEME-1567)
This PR only proposes making the dependency on `@gympass/yoga-icons` a peer dependency in `@gympass/yoga`.
Since client applications generally tend to depend directly on the `@gympass/yoga-icons` package, its presence as a direct dependency on the `@gympass/yoga` package often causes the application to have dependency duplication problems. In many cases, package managers such as Yarn do not resolve the conflict (see [_duplicate package errors_](https://microsoft.github.io/rnx-kit/docs/guides/bundling#running-the-bundler)) even by running deduplication programs, which can be problematic for optimizing the js bundle.
Below is evidence collected from initiatives in the Wellhub …
=> fix(package): moves yoga-icons dep to peer dependencies

packages/doc/content/components/components/autocomplete/index.mdx, packages/yoga/src/AutoComplete/web/AutoComplete.jsx
[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DSC-2039)
This PR adds a new prop called `highlightFirst` in the `Autocomplete` component to highlight the first option whenever Autocomplete is restarted.
The first one (Deaful) already exists, and the second one is with the prop `defaultHighlightedIndex={0}`
https://github.com/user-attachments/assets/4c31fc81-c776-4e73-8a2b-668609ca46f0
=>   🚀 feat: add highlightFirst prop in AutoComplete web component 
